package me.elhizazi.Castix.privilege.ui

/**
 * Secondary/localization extension point.
 *
 * Keep additional languages here so AppStrings.kt remains focused on the
 * primary English/Arabic API. Adding a new language should normally require
 * changes only in this file: add its AppLanguage metadata and its string map
 * to [maps].
 */
internal object AppStringsSecondary {
    val languages = listOf(
        AppLanguage(code = "zh", nativeName = "简体中文", englishName = "Chinese"),
        AppLanguage(code = "ja", nativeName = "日本語", englishName = "Japanese")
    ) + AppStringsEuropean.languages

    val maps: Map<String, Map<String, String>>
        get() = mapOf(
            "zh" to zh,
            "ja" to ja
        ) + AppStringsEuropean.maps

    val zh = mapOf(
        "nav_home" to "首页",
        "nav_amoled" to "AMOLED",
        "nav_engines" to "引擎",
        "nav_settings" to "设置",
        "app_title" to "Castix",
        "app_subtitle" to "关闭屏幕并保持后台播放",
        "app_tag_pro" to "专业版",
        "black_screen_title" to "AMOLED 黑屏",
        "black_screen_desc" to "在媒体继续播放时关闭屏幕像素",
        "black_screen_action_on" to "关闭屏幕",
        "black_screen_action_off" to "退出黑屏",
        "black_screen_tip" to "提示：双击任意位置退出，或单击显示时钟 10 秒。",
        "save_power_badge" to "节省 100% 屏幕电量",
        "black_screen_unlock_hint" to "双击解锁",
        "black_screen_playing_fallback" to "后台播放中",
        "black_screen_active_state" to "已激活 (像素已关闭)",
        "black_screen_inactive_state" to "屏幕开启",
        "floating_title" to "悬浮按钮",
        "floating_desc" to "视频播放器上的快捷息屏按钮",
        "floating_status_enabled" to "已启用 • 就绪",
        "floating_status_disabled" to "已禁用",
        "floating_status_active" to "已激活",
        "floating_mode_label" to "显示模式",
        "floating_mode_selected_apps" to "仅选定应用",
        "floating_mode_always_visible" to "始终可见",
        "floating_selected_apps_count" to "已选定应用",
        "floating_scope_label" to "显示范围：",
        "scope_selected_apps" to "仅选定应用",
        "scope_all_apps" to "始终在屏幕上",
        "selected_apps_count" to "个应用已选",
        "btn_choose_apps" to "选择应用",
        "target_apps" to "目标应用",
        "floating_btn_manage_apps" to "目标应用",
        "overlay_perm_required" to "需要悬浮窗权限",
        "overlay_perm_warning_title" to "需要悬浮窗权限",
        "overlay_perm_warning_desc" to "需要显示在其他应用上层的权限，以便在保持播放的同时关闭屏幕像素。",
        "open_settings" to "打开设置",
        "grant_via_engine" to "通过引擎自动授权",
        "accessibility_warning" to "无障碍服务已禁用。检测目标应用打开时需要此权限。",
        "enable_accessibility" to "启用服务",
        "service_title" to "后台服务",
        "service_subtitle" to "保持音频播放并绕过锁屏暂停",
        "service_running" to "已激活 • 已连接",
        "service_stopped" to "已停止",
        "service_status_label" to "服务状态",
        "service_btn_start" to "启动服务",
        "service_btn_stop" to "停止服务",
        "service_btn_restart" to "重新启动",
        "service_mode_label" to "系统优先级：",
        "service_lockscreen_bypass_label" to "唤醒锁绕过 (WakeLock)",
        "service_wakelock_engaged" to "已激活 (音频受保护)",
        "service_wakelock_idle" to "待机",
        "status_bar_notice" to "可从快速设置磁贴访问",
        "lock_screen_title" to "锁屏兼容性",
        "lock_screen_subtitle" to "设备锁定时音频继续播放",
        "lock_screen_phone_protection" to "安全性",
        "lock_screen_secured" to "已保护 (PIN / 生物识别)",
        "lock_screen_power_saving" to "电池优化",
        "lock_screen_unrestricted" to "已豁免 (无限制)",
        "lock_screen_restricted" to "已优化 (可能暂停音频)",
        "lock_screen_ambient_mode" to "息屏显示 (AOD)",
        "lock_screen_ambient_ready" to "兼容",
        "btn_fix_battery_optimization" to "豁免电池优化",
        "lock_screen_tip" to "音频和媒体通知在锁屏状态下保持活动，不会意外暂停。",
        "target_apps_sheet_title" to "目标应用程序",
        "target_apps_sheet_subtitle" to "悬浮按钮仅在这些应用打开时自动出现",
        "search_apps_placeholder" to "按名称或包名搜索...",
        "btn_select_all" to "全选",
        "btn_deselect_all" to "取消全选",
        "btn_clear_all" to "清除选择",
        "btn_done" to "完成",
        "no_apps_found" to "未找到匹配的应用程序",
        "engine_desc_shizuku" to "通过已授权的 Shizuku 服务提供 Binder IPC 连接。",
        "engine_desc_dhizuku" to "通过设备所有者权限控制系统策略和后台任务。",
        "engine_desc_root" to "通过设备的 Root 服务直接执行系统命令。",
        "engine_desc_lsposed" to "通过 LSPosed 框架向受支持的进程注入运行时 Hook。",
        "engine_desc_lspatch" to "将无 Root 的 Xposed Hook 嵌入实际修补过的 APK。",
        "engine_desc_accessibility" to "使用 Android 无障碍服务检测前台应用并支持播放控制。",
        "engine_arch_shizuku" to "远程 Binder 服务（ADB/Root）",
        "engine_arch_dhizuku" to "设备所有者策略服务",
        "engine_arch_root" to "Root Shell（UID 0）",
        "engine_arch_lsposed" to "ART/Zygote 运行时 Hook",
        "engine_arch_lspatch" to "无 Root APK/Dex 加载器",
        "engine_arch_accessibility" to "Android 无障碍框架",
        "engine_status_detail_active" to "此引擎当前已获得授权，可以使用。",
        "engine_status_detail_inactive" to "已检测到此引擎，但当前未启用。",
        "engine_status_detail_permission" to "引擎已安装或运行，但 Castix 仍需要相应权限。",
        "engine_status_detail_available" to "可供使用，但当前未激活。",
        "engine_status_detail_missing" to "未在设备上检测到此引擎。",
        "engine_status_detail_error" to "此引擎报告了错误，目前无法使用。",
        "engine_root_detected" to "已检测到：%1\$s",
        "engine_root_kernel_note" to "在 %1\$s/APatch 上，Root 请求可能不会自动弹出。请打开管理器，在 Superuser 中找到 Castix 并启用权限。",
        "engine_root_app_note" to "已检测到 %1\$s。打开它以检查 Castix 的 Superuser 权限。",
        "engine_lsposed_activation_title" to "在 LSPosed 中启用 Castix",
        "engine_lsposed_activation_text" to "打开 LSPosed Manager，在 Modules 中启用 Castix 模块，选择目标应用，然后重新启动这些应用。",
        "engine_detail_root" to "Root 引擎通过设备的超级用户服务，以 UID 0 执行系统命令。",
        "engine_detail_shizuku" to "Shizuku 通过其系统服务为 Castix 提供已授权的 Binder IPC 访问。",
        "engine_detail_dhizuku" to "Dhizuku 通过设备所有者权限，为受支持的操作提供系统策略访问。",
        "engine_detail_lsposed" to "LSPosed 将 Castix Hook 注入受支持的 ART/Zygote 进程。只有在 Castix 模块实际启用并由 LSPosed 加载后才会生效。",
        "engine_detail_lspatch" to "LSPatch 将 Castix Xposed Hook 嵌入已修补的 APK。只有在实际修补并加载该 APK 后才会生效。",
        "engine_detail_accessibility" to "Android 无障碍服务无需 Root，可用于检测前台应用及相关控制。",
        "engine_setup_root" to "1. 确保设备已 Root 并安装 Root 管理器。\n2. 点击下方“请求 Root 权限”。\n3. 在 Root 管理器中允许 Castix。",
        "engine_setup_shizuku" to "1. 安装 Shizuku。\n2. 开启无线调试。\n3. 启动 Shizuku 服务。\n4. 授予 Castix 权限。",
        "engine_setup_dhizuku" to "1. 安装 Dhizuku。\n2. 按其官方 ADB 步骤将其设为设备所有者。\n3. 在 Dhizuku 中授予 Castix 权限。",
        "engine_setup_lsposed" to "1. 在 Root 管理器中启用 Zygisk。\n2. 安装并启动 LSPosed。\n3. 启用 Castix 模块并选择目标应用。\n4. 重启目标应用。",
        "engine_setup_lspatch" to "1. 安装 LSPatch。\n2. 选择目标播放器 APK。\n3. 使用 Castix 修补 APK 并安装修补后的版本。",
        "engine_setup_accessibility" to "1. 点击下方“请求权限”。\n2. Android 无障碍设置将自动打开。\n3. 启用 Castix 服务。",
        "engine_sheet_title" to "特权引擎详细信息",
        "engine_status_label" to "状态",
        "engine_privilege_label" to "特权级别",
        "engine_capabilities_label" to "引擎功能",
        "engine_commands_label" to "快速命令",
        "btn_request_perm" to "授予权限",
        "btn_grant_overlay" to "授予权限",
        "btn_test_engine" to "测试引擎",
        "btn_close" to "关闭",
        "btn_cancel" to "取消",
        "btn_apply" to "应用",
        "btn_refresh" to "刷新状态",
        "btn_dismiss" to "忽略",
        "btn_execute" to "执行",
        "btn_clear" to "清除日志",
        "lang_sheet_title" to "应用语言",
        "lang_sheet_subtitle" to "选择您的首选语言。界面布局方向将立即更新。",
        "lang_search_placeholder" to "搜索语言...",
        "future_languages_note" to "可通过标准 Android strings.xml 资源轻松添加新语言。",
        "lang_auto" to "跟随系统 (自动)",
        "lang_en" to "English (英语)",
        "lang_ar" to "Arabic (阿拉伯语)",
        "hex_sheet_title" to "自定义主题色",
        "hex_sheet_subtitle" to "点击或拖动色轮以选择您喜欢的主题色。",
        "hex_input_label" to "HEX 代码 (例如 #00E5FF)",
        "hex_custom_button" to "自定义 Hex",
        "settings_appearance" to "外观和主题",
        "settings_appearance_desc" to "控制外观、主题和动态 Android 颜色",
        "settings_display_mode" to "显示模式",
        "settings_color_palette" to "调色板",
        "settings_ui_scale_title" to "界面与字体缩放",
        "settings_ui_scale_desc" to "调整界面缩放和排版。",
        "settings_theme" to "主题模式",
        "settings_language" to "应用语言",
        "settings_language_current" to "当前",
        "settings_accent" to "主题色",
        "settings_black_screen" to "黑屏自定义",
        "settings_clock_style" to "时钟样式",
        "settings_show_app_badge" to "显示活动应用徽章",
        "settings_floating_button" to "悬浮按钮自定义",
        "settings_floating_size" to "悬浮按钮大小",
        "settings_floating_alpha" to "悬浮按钮不透明度",
        "settings_about" to "关于与支持",
        "settings_how_to_use" to "快速设置磁贴指南",
        "settings_support" to "技术支持与社区",
        "settings_version" to "正式版本 1.0",
        "theme_dark" to "深色",
        "theme_light" to "浅色",
        "theme_system" to "系统默认",
        "color_sapphire" to "蓝宝石",
        "color_emerald" to "翡翠绿",
        "color_amethyst" to "紫水晶",
        "color_sunset" to "日落黄",
        "color_crimson" to "深红",
        "color_teal" to "青色",
        "connected_status" to "已连接",
        "settings_dynamic_m3" to "动态 M3",
        "engine_core_title" to "特权引擎 (Castix Core)",
        "engine_prefix" to "引擎：",
        "engine_active" to "已激活",
        "engine_status_desc" to "系统引擎已连接，准备好绕过后台限制并关闭屏幕像素。",
        "engine_check_button" to "检查特权并重新初始化",
        "settings_support_email" to "support@elhizazi.me",
        "settings_version_info" to "版本 1.0 (Build 2026.09) • Android 17 架构",
        "clock_style_digital" to "数字时钟",
        "clock_style_minimal" to "极简风格",
        "clock_style_glow" to "霓虹发光",
        "clock_style_analog" to "经典指针",
        "clock_style_retro" to "复古翻页",
        "clock_style_text_word" to "文字时钟",
        "clock_style_pixel_airy" to "Pixel 轻盈",
        "clock_style_material_expressive" to "Material 表达式",
        "clock_customization_title" to "时钟工作室",
        "clock_customization_desc" to "精细调整 AMOLED 时钟",
        "clock_scale_label" to "大小",
        "clock_position_label" to "垂直位置",
        "clock_spacing_label" to "间距",
        "clock_style_large_center" to "大号居中",
        "clock_style_stacked" to "上下时间",
        "clock_style_mono_line" to "等宽单行",
        "clock_style_dashboard" to "数据仪表盘",
        "amoled_preview_title" to "AMOLED 实时预览",
        "amoled_preview_desc" to "使用 100% 纯黑像素的实时预览以节省电池电量",
        "amoled_btn_test" to "立即测试息屏",
        "amoled_clock_section" to "时钟设计与样式",
        "amoled_clock_section_desc" to "选择时钟外观和息屏布局",
        "amoled_display_elements" to "屏幕显示元素",
        "amoled_display_elements_desc" to "配置息屏期间显示的元素以节省电量",
        "show_battery_label" to "电池电量与健康",
        "show_battery_desc" to "以微妙的霓虹发光显示当前电池电量",
        "show_date_label" to "日期与星期",
        "show_date_desc" to "在时钟下方显示当前日期和日历",
        "show_app_badge_label" to "活动应用徽章",
        "show_app_badge_desc" to "显示后台播放的应用程序名称",
        "show_playback_timer_label" to "播放会话计时器",
        "show_playback_timer_desc" to "跟踪连续收听持续时间",
        "burn_in_label" to "像素位移 (防烧屏保护)",
        "burn_in_desc" to "定期轻微移动元素以保护 OLED 显示屏",
        "custom_inscription_label" to "自定义签名 / 标语",
        "custom_inscription_desc" to "在息屏期间显示个性化短语",
        "custom_inscription_hint" to "输入自定义标语...",
        "floating_customization_section" to "悬浮按钮外观",
        "floating_customization_desc" to "调整悬浮触发器的大小、不透明度和触觉反馈",
        "floating_size_label" to "按钮大小",
        "floating_alpha_label" to "按钮不透明度",
        "floating_haptic_label" to "触觉反馈",
        "floating_haptic_desc" to "按下悬浮按钮时短暂振动",
        "qs_tile_tip" to "快速设置磁贴：从屏幕顶部向下滑动，点击“编辑”，然后将“关闭屏幕”磁贴拖入活动磁贴中。",
        "engine_selector_title" to "特权引擎",
        "engine_selector_desc" to "选择并激活您设备上的特权引擎",
        "active_engine_label" to "活动引擎",
        "engine_ready" to "已激活且已授权",
        "engine_not_ready" to "未激活 • 需要设置",
        "status_escalation_tier" to "特权层级",
        "status_service_running" to "服务状态",
        "status_overlay_perm" to "悬浮窗权限",
        "status_granted" to "已授予",
        "status_denied" to "已拒绝",
        "status_active" to "已激活",
        "status_checking" to "正在检查…",
        "status_available" to "可用",
        "status_perm_needed" to "需要权限",
        "status_inactive" to "服务已停止",
        "status_missing" to "未安装",
        "status_error" to "错误",
        "status_none_active" to "未激活",
        "engine_none_active_hint" to "当前没有活动的特权引擎。选择并激活引擎以获得完全控制。",
        "engine_btn_grant_perm" to "授予权限",
        "engine_btn_setup_guide" to "设置指南",
        "engine_btn_start_service" to "启动服务",
        "engine_btn_open_lsposed" to "打开 LSPosed",
        "engine_btn_open_manager" to "打开管理器",
        "engine_btn_activate" to "激活",
        "engine_btn_retry" to "重试",
        "playback_utility_title" to "播放优化",
        "playback_utility_subtitle" to "系统级后台绕过",
        "btn_apply_all" to "全部应用",
        "task_doze_title" to "电池豁免 (Doze 模式)",
        "task_doze_desc" to "在深度休眠期间保持音频管道活动。",
        "task_standby_title" to "待机存储分区活跃",
        "task_standby_desc" to "保证 CPU 和网络配额，不受系统限制。",
        "task_appops_title" to "后台 AppOps",
        "task_appops_desc" to "授予无限制的后台执行特权。",
        "task_phantom_title" to "禁用幻影进程杀手",
        "task_phantom_desc" to "防止 Android 杀死子播放进程。",
        "lsposed_spoofing_title" to "音频焦点拦截 (LSPosed)",
        "lsposed_spoofing_desc" to "阻止降低音量和放弃焦点的请求。",
        "task_enforced" to "已生效",
        "btn_reapply" to "重新应用",
        "terminal_title" to "特权控制台",
        "terminal_subtitle" to "执行媒体管理和系统 Shell 命令",
        "terminal_placeholder" to "输入 shell 命令 (例如 dumpsys media_session)...",
        "terminal_card_title" to "特权控制台",
        "btn_clear_terminal" to "清除日志",
        "terminal_input_hint" to "输入 shell 命令...",
        "btn_run" to "运行",
        "terminal_empty_msg" to "控制台为空。运行命令或绕过任务。",
        "quick_commands_label" to "快速命令：",
        "settings_black_screen_subtitle" to "自定义时钟样式、徽章和息屏行为",
        "settings_show_app_badge_desc" to "在息屏期间显示活动的后台应用程序",
        "settings_double_tap_wake" to "双击唤醒",
        "settings_double_tap_wake_desc" to "双击黑屏上的任意位置即可解锁",
        "settings_zero_brightness" to "零背光 (0%)",
        "settings_zero_brightness_desc" to "将背光调至硬件最低水平以节省电量",
        "settings_floating_subtitle" to "调整悬浮按钮的大小和不透明度",
        "settings_about_subtitle" to "用户指南、快速设置磁贴和支持",
        "settings_version_detail" to "版本 1.0 (Build 2026.09) • 兼容 Android 17",
        "settings_edition" to "Castix 生产版",
        "app_name" to "Castix",
        "subtitle_arch" to "Android 17 系统架构师",
        "btn_enable_accessibility" to "启用无障碍服务",
        "btn_auto_grant_engine" to "通过引擎自动授权",
        "floating_perm_required_title" to "需要悬浮窗权限",
        "floating_perm_required_desc" to "悬浮按钮需要显示在其他应用上层的权限。",
        "floating_accessibility_tip_title" to "应用即时检测",
        "floating_accessibility_tip_desc" to "启用 Castix 无障碍服务以零延迟检测视频应用。",
        "lock_screen_unsecured" to "仅滑动",
        "lock_screen_wakelock" to "唤醒锁",
        "lock_screen_wakelock_active" to "已激活",
        "lock_screen_wakelock_ready" to "待机",
        "lock_screen_battery_opt" to "省电模式",
        "lock_screen_battery_unrestricted" to "无限制",
        "lock_screen_battery_restricted" to "已限制",
        "lock_screen_btn_disable_battery_opt" to "禁用电池限制",
        "lock_screen_battery_auto_grant" to "自动白名单 (Root/Shizuku)",
        "permission_required_tag" to "需要权限",
        "black_screen_status_engaged" to "屏幕已关闭",
        "lock_screen_feature_1_title" to "安全锁屏支持",
        "lock_screen_feature_1_desc" to "在锁屏后安全运行，不暴露数据。",
        "lock_screen_feature_2_title" to "不间断音频",
        "lock_screen_feature_2_desc" to "媒体会话保持持续的前台优先级。",
        "lock_screen_feature_3_title" to "双击解锁",
        "lock_screen_feature_3_desc" to "双击任意位置立即退出黑屏。",
        "lock_screen_btn_security_settings" to "安全设置",
        "target_apps_selected_summary" to "已选择 %1\$d 个应用程序",
        "target_apps_empty" to "未找到匹配的应用",
        "target_apps_media_badge" to "媒体播放器",
        "section_engine_selector" to "特权提权策略",
        "section_service_status" to "系统后端状态",
        "section_playback_ops" to "后台播放与保活工具",
        "section_terminal" to "特权命令控制台",
        "engines_title" to "系统特权引擎",
        "engines_subtitle" to "一键切换或激活特权引擎",
        "engine_details_btn" to "引擎详情",
        "engine_perm_steps_title" to "授权步骤",
        "engine_capabilities_title" to "功能",
        "shizuku_name" to "Shizuku",
        "dhizuku_name" to "Dhizuku",
        "root_name" to "Root (su)",
        "lsposed_name" to "LSPosed",
        "lspatch_name" to "LSPatch (免Root)",
        "accessibility_name" to "无障碍服务",
        "accessibility_service_desc" to "允许 Castix 即时检测前台应用并保持播放优先级。",
        "playback_bypasses_title" to "后台播放操作",
        "playback_bypasses_subtitle" to "系统级防暂停绕过",
        "btn_execute_all" to "执行所有绕过",
        "lsposed_hook_title" to "LSPosed 媒体拦截",
        "lsposed_hook_desc" to "注入媒体会话拦截，防止息屏时暂停",
        "terminal_input_placeholder" to "输入 shell 命令...",
        "btn_clear_logs" to "清除控制台",
        "terminal_empty_logs" to "控制台输出为空。请执行任务或命令。",
        "settings_language_choose_title" to "选择应用语言",
        "settings_language_choose_desc" to "选择您首选的界面语言 (支持 RTL / LTR)",
        "settings_double_tap" to "双击唤醒",
        "settings_double_tap_desc" to "双击黑屏上的任意位置立即退出",
        "settings_floating_button_subtitle" to "调整空心圆形悬浮盘的大小和不透明度",
        "hex_presets_label" to "预设调色板",
        "how_to_use_step_1" to "向下滑动通知栏两次以展开所有快速设置磁贴。",
        "how_to_use_step_2" to "点击铅笔图标或“编辑”按钮以管理可用磁贴。",
        "how_to_use_step_3" to "将 Castix 的“关闭屏幕”磁贴拖到您的活动磁贴中。",
        "how_to_use_step_4" to "现在，在播放视频或音乐时，点击该磁贴即可关闭所有像素，后台播放将无缝继续！",
        "support_desc" to "Castix 致力于实现无缝的后台播放和纯净的 AMOLED 息屏省电。",
        "support_channel" to "官方支持频道",
        "notification_title" to "Castix • 后台播放进行中",
        "notification_text" to "音频保护运行中 • 点击以关闭屏幕或打开应用",
        "notification_action_black_screen" to "关闭屏幕 (黑屏)",
        "notification_action_stop" to "停止服务",
        "battery_stable" to "电池稳定",
        "runtime_environment" to "运行环境",
        "target_platform" to "目标平台",
        "api_level" to "API 级别",
        "selinux_mode" to "SELinux 模式",
        "device_hardware" to "设备硬件",
        "architecture" to "架构",
        "compatibility_banner_title" to "当前系统：Android %1\$s (API %2\$d)",
        "compatibility_banner_desc" to "所有后台播放绕过和进程保护工具均与您的系统完全兼容。",
        "engine_available_active" to "已激活",
        "engine_permission_needed" to "需要权限",
        "btn_activate" to "激活",
        "service_status_title" to "系统后端状态",
        "live_ipc_monitors" to "实时 IPC 监视器",
        "status_perm_required" to "需要权限",
        "black_screen_continuous_play" to "持续后台播放",
        "black_screen_app_playing" to "%1\$s • 持续播放",
        "black_screen_long_press_unlock" to "长按解锁",
        "engine_dialog_guide_title" to "Architecture & Diagnostics",
        "engine_dialog_current_status" to "Current status:",
        "engine_dialog_build" to "Build: %1\$s",
        "engine_dialog_open_manager" to "Open %1\$s App",
        "engine_dialog_root_note" to "%1\$s detected. Open it to manage superuser access.",
        "engine_dialog_lsposed_note" to "Open LSPosed Manager, enable the Castix module, select target applications, then restart the target apps.",
        "engine_dialog_root_request" to "Request Root (su)",
        "engine_dialog_accessibility_request" to "Open Accessibility Settings",
        "engine_dialog_close" to "Close",
        "engine_dialog_root_steps" to "1. Tap 'Request Root (su)' below to send a request to the root service.\n2. Approve the permission request in your root manager.",
        "engine_dialog_shizuku_steps" to "3. Open Shizuku, pair with the service, then start it.\n4. Tap 'Grant Permission' below to authorize Castix.",
        "engine_dialog_dhizuku_step" to "3. Open Dhizuku and grant permission to Castix.",
        "engine_dialog_lsposed_step" to "3. Open LSPosed, enable the Castix module, and select the target media apps.",
        "engine_dialog_accessibility_steps" to "1. Tap 'Grant Permission' below.\n2. The Accessibility settings screen will open automatically.",
        "lsposed_dialog_title" to "Activate LSPosed Module",
        "lsposed_dialog_version" to "LSPosed 2.2.0 (API 102 Zygisk)",
        "lsposed_dialog_close" to "Close",
        "lsposed_dialog_framework_status" to "Framework status:",
        "lsposed_dialog_framework_active" to "LSPosed is enabled and active on your device",
        "lsposed_dialog_module_status" to "Castix module status:",
        "lsposed_dialog_instructions_title" to "How to activate Castix inside LSPosed:",
        "lsposed_dialog_instructions" to "1. Open the LSPosed Manager installed on your device.",
        "lsposed_dialog_confirm" to "Confirm module activation (I enabled it in LSPosed)",
        "lsposed_dialog_rescan" to "Re-check module status automatically",
        "shizuku_dialog_title" to "Request Shizuku / Shevery Permission",
        "shizuku_dialog_subtitle" to "System Binder IPC permission without root",
        "shizuku_dialog_close" to "Close",
        "shizuku_dialog_installed" to "Installed application:",
        "shizuku_dialog_server_status" to "Shizuku server status:",
        "shizuku_dialog_castix_permission" to "Castix permission:",
        "shizuku_dialog_activation_title" to "Activation method:",
        "shizuku_dialog_activation_steps" to "1. If the service is stopped, open Shizuku, Shevery, or Shizuku+ and start it (via wireless debugging or root).\n2. After the service starts, tap 'Direct Permission Request' below to authorize Castix.",
        "shizuku_dialog_permission_request" to "Permission already granted (request again)",
        "shizuku_dialog_direct_request" to "Direct Permission Request",
        "shizuku_dialog_open_manager" to "Open Manager App (%1\$s)",
        "shizuku_dialog_rescan" to "Re-check connection and refresh status",
        "terminal_prompt" to "android17@sysarchitect ~ #",
        "notification_service_title" to "Castix • Background Playback",
        "notification_service_text" to "Protection is active • Tap to turn off the screen or open the app",
        "notification_action_black_screen_ui" to "Turn Screen Off (Black Screen)",
        "black_screen_session_timer" to "Active Session: %1\$dm",
        "amoled_preview_time" to "TIME • %1\$s",
        "amoled_preview_battery" to "88%% • Battery Optimal",
        "amoled_preview_session" to "Active Session: 25m",
        "amoled_preview_now_playing" to "Now Playing: YouTube",

        "black_screen_clock_time_ar" to "TIME • %1\$d:%2\$d",
        "black_screen_clock_time_en" to "TIME • %1\$d:%2\$d",

    )

    val ja = mapOf(
        "nav_home" to "ホーム",
        "nav_amoled" to "AMOLED",
        "nav_engines" to "エンジン",
        "nav_settings" to "設定",
        "app_title" to "Castix",
        "app_subtitle" to "画面オフ・バックグラウンド再生",
        "app_tag_pro" to "PRO",
        "black_screen_title" to "AMOLED ブラックスクリーン",
        "black_screen_desc" to "メディア再生を続行したまま画面のピクセルをオフにします",
        "black_screen_action_on" to "画面をオフ",
        "black_screen_action_off" to "ブラックスクリーンを終了",
        "black_screen_tip" to "ヒント: 画面の任意の場所をダブルタップして終了するか、シングルタップして時計を10秒間表示します。",
        "save_power_badge" to "100% 電力を節約",
        "black_screen_unlock_hint" to "ダブルタップでロック解除",
        "black_screen_playing_fallback" to "バックグラウンドで再生中",
        "black_screen_active_state" to "アクティブ (ピクセル オフ)",
        "black_screen_inactive_state" to "画面 オン",
        "floating_title" to "フローティングボタン",
        "floating_desc" to "動画プレーヤー上に表示されるクイック画面オフボタン",
        "floating_status_enabled" to "有効 • 準備完了",
        "floating_status_disabled" to "無効",
        "floating_status_active" to "アクティブ",
        "floating_mode_label" to "表示モード",
        "floating_mode_selected_apps" to "選択したアプリ",
        "floating_mode_always_visible" to "常に表示",
        "floating_selected_apps_count" to "個のアプリを選択済み",
        "floating_scope_label" to "表示範囲:",
        "scope_selected_apps" to "選択したアプリのみ",
        "scope_all_apps" to "常に画面に表示",
        "selected_apps_count" to "個のアプリを選択済み",
        "btn_choose_apps" to "アプリを選択",
        "target_apps" to "対象アプリ",
        "floating_btn_manage_apps" to "対象アプリ",
        "overlay_perm_required" to "オーバーレイ権限が必要です",
        "overlay_perm_warning_title" to "オーバーレイ権限が必要です",
        "overlay_perm_warning_desc" to "再生を維持しながら画面を暗くするには、他のアプリの上に表示する権限が必要です。",
        "open_settings" to "設定を開く",
        "grant_via_engine" to "エンジン経由で自動許可",
        "accessibility_warning" to "ユーザー補助サービスが無効です。対象アプリが起動したことを検出するために必要です。",
        "enable_accessibility" to "サービスを有効にする",
        "service_title" to "バックグラウンドサービス",
        "service_subtitle" to "音声再生を維持し、ロック画面での停止を回避します",
        "service_running" to "アクティブ • 接続済み",
        "service_stopped" to "停止中",
        "service_status_label" to "サービス状態",
        "service_btn_start" to "サービスを開始",
        "service_btn_stop" to "サービスを停止",
        "service_btn_restart" to "再起動",
        "service_mode_label" to "システム優先度:",
        "service_lockscreen_bypass_label" to "ウェイクロックのバイパス",
        "service_wakelock_engaged" to "アクティブ (音声保護中)",
        "service_wakelock_idle" to "スタンバイ",
        "status_bar_notice" to "クイック設定パネルからアクセス可能",
        "lock_screen_title" to "ロック画面の互換性",
        "lock_screen_subtitle" to "デバイスがロックされていても音声再生を継続します",
        "lock_screen_phone_protection" to "セキュリティ",
        "lock_screen_secured" to "保護済み (PIN / 生体認証)",
        "lock_screen_power_saving" to "バッテリー最適化",
        "lock_screen_unrestricted" to "除外済み (制限なし)",
        "lock_screen_restricted" to "最適化済み (停止する可能性あり)",
        "lock_screen_ambient_mode" to "Always-On Display",
        "lock_screen_ambient_ready" to "互換性あり",
        "btn_fix_battery_optimization" to "バッテリー最適化から除外",
        "lock_screen_tip" to "音声およびメディア通知は、ロック画面でも予期せず停止することなくアクティブなままになります。",
        "target_apps_sheet_title" to "対象アプリケーション",
        "target_apps_sheet_subtitle" to "これらのアプリを開いたときに自動的にフローティングボタンを表示します",
        "search_apps_placeholder" to "名前またはパッケージで検索...",
        "btn_select_all" to "すべて選択",
        "btn_deselect_all" to "すべて選択解除",
        "btn_clear_all" to "選択をクリア",
        "btn_done" to "完了",
        "no_apps_found" to "一致するアプリケーションが見つかりません",
        "engine_desc_shizuku" to "認証済みの Shizuku サービスを介して Binder IPC 接続を提供します。",
        "engine_desc_dhizuku" to "デバイス所有者権限を利用してシステムポリシーとバックグラウンド処理を管理します。",
        "engine_desc_root" to "端末の Root サービスを介してシステムコマンドを直接実行します。",
        "engine_desc_lsposed" to "LSPosed フレームワークを介して対応プロセスへランタイム Hook を注入します。",
        "engine_desc_lspatch" to "Root 不要の Xposed Hook を実際にパッチした APK に組み込みます。",
        "engine_desc_accessibility" to "Android ユーザー補助サービスで前面アプリを検出し、再生制御を支援します。",
        "engine_arch_shizuku" to "リモート Binder サービス（ADB/Root）",
        "engine_arch_dhizuku" to "デバイス所有者ポリシーサービス",
        "engine_arch_root" to "Root Shell（UID 0）",
        "engine_arch_lsposed" to "ART/Zygote ランタイム Hook",
        "engine_arch_lspatch" to "Root 不要 APK/Dex ローダー",
        "engine_arch_accessibility" to "Android ユーザー補助フレームワーク",
        "engine_status_detail_active" to "このエンジンは現在認証済みで、使用可能です。",
        "engine_status_detail_inactive" to "このエンジンは検出されていますが、現在は有効ではありません。",
        "engine_status_detail_permission" to "エンジンはインストールまたは実行されていますが、Castix に権限が必要です。",
        "engine_status_detail_available" to "使用できますが、現在は有効ではありません。",
        "engine_status_detail_missing" to "このエンジンは端末上で検出されませんでした。",
        "engine_status_detail_error" to "このエンジンでエラーが発生したため、使用できません。",
        "engine_root_detected" to "検出：%1\$s",
        "engine_root_kernel_note" to "%1\$s/APatch では Root 要求が自動表示されない場合があります。管理アプリを開き、Superuser で Castix を見つけて権限を有効にしてください。",
        "engine_root_app_note" to "%1\$s を検出しました。開いて Castix の Superuser 権限を確認してください。",
        "engine_lsposed_activation_title" to "LSPosed で Castix を有効にする",
        "engine_lsposed_activation_text" to "LSPosed Manager を開き、Modules で Castix モジュールを有効にし、対象アプリを選択してからアプリを再起動してください。",
        "engine_detail_root" to "Root エンジンは端末のスーパーユーザーサービスを使用し、UID 0 でシステムコマンドを実行します。",
        "engine_detail_shizuku" to "Shizuku はシステムサービスを介して Castix に認証済み Binder IPC アクセスを提供します。",
        "engine_detail_dhizuku" to "Dhizuku はデバイス所有者権限を介して、対応する操作のシステムポリシーへアクセスします。",
        "engine_detail_lsposed" to "LSPosed は対応する ART/Zygote プロセスへ Castix の Hook を注入します。Castix モジュールが実際に有効化され、LSPosed によってロードされた場合のみ動作します。",
        "engine_detail_lspatch" to "LSPatch は Castix の Xposed Hook をパッチ済み APK に組み込みます。実際にパッチされロードされた APK 内でのみ動作します。",
        "engine_detail_accessibility" to "Android ユーザー補助サービスは Root 不要で、前面アプリの検出などに使用できます。",
        "engine_setup_root" to "1. Root 管理アプリがインストールされ、端末が Root 化されていることを確認します。\n2. 下の「Root 権限を要求」をタップします。\n3. Root 管理アプリで Castix を許可します。",
        "engine_setup_shizuku" to "1. Shizuku をインストールします。\n2. ワイヤレスデバッグを有効にします。\n3. Shizuku サービスを起動します。\n4. Castix に権限を付与します。",
        "engine_setup_dhizuku" to "1. Dhizuku をインストールします。\n2. 公式の ADB 手順でデバイス所有者に設定します。\n3. Dhizuku で Castix に権限を付与します。",
        "engine_setup_lsposed" to "1. Root 管理アプリで Zygisk を有効にします。\n2. LSPosed をインストールして起動します。\n3. Castix モジュールを有効にして対象アプリを選択します。\n4. 対象アプリを再起動します。",
        "engine_setup_lspatch" to "1. LSPatch をインストールします。\n2. 対象プレーヤー APK を選択します。\n3. Castix を使って APK をパッチし、パッチ済み APK をインストールします。",
        "engine_setup_accessibility" to "1. 下の「権限を要求」をタップします。\n2. Android のユーザー補助設定が開きます。\n3. Castix サービスを有効にします。",
        "engine_sheet_title" to "特権エンジンの詳細",
        "engine_status_label" to "状態",
        "engine_privilege_label" to "特権レベル",
        "engine_capabilities_label" to "エンジンの機能",
        "engine_commands_label" to "クイックコマンド",
        "btn_request_perm" to "権限を許可",
        "btn_grant_overlay" to "権限を許可",
        "btn_test_engine" to "エンジンをテスト",
        "btn_close" to "閉じる",
        "btn_cancel" to "キャンセル",
        "btn_apply" to "適用",
        "btn_refresh" to "状態を更新",
        "btn_dismiss" to "無視",
        "btn_execute" to "実行",
        "btn_clear" to "ログを消去",
        "lang_sheet_title" to "アプリの言語",
        "lang_sheet_subtitle" to "希望する言語を選択してください。レイアウトの方向は即座に更新されます。",
        "lang_search_placeholder" to "言語を検索...",
        "future_languages_note" to "標準のAndroid strings.xmlリソースを使用して簡単に新しい言語を追加できます。",
        "lang_auto" to "システムに従う (自動)",
        "lang_en" to "English (英語)",
        "lang_ar" to "Arabic (アラビア語)",
        "hex_sheet_title" to "カスタムアクセントカラー",
        "hex_sheet_subtitle" to "カラーホイールをタップまたはドラッグして色を選択します。",
        "hex_input_label" to "HEX コード (例: #00E5FF)",
        "hex_custom_button" to "カスタム Hex",
        "settings_appearance" to "外観とテーマ",
        "settings_appearance_desc" to "外観、テーマ、Androidのダイナミックカラーを制御します",
        "settings_display_mode" to "表示モード",
        "settings_color_palette" to "カラーパレット",
        "settings_ui_scale_title" to "UIとフォントの拡大率",
        "settings_ui_scale_desc" to "インターフェースのスケールとタイポグラフィを調整します。",
        "settings_theme" to "テーマモード",
        "settings_language" to "アプリの言語",
        "settings_language_current" to "現在",
        "settings_accent" to "アクセントカラー",
        "settings_black_screen" to "ブラックスクリーンのカスタマイズ",
        "settings_clock_style" to "時計スタイル",
        "settings_show_app_badge" to "アクティブアプリのバッジを表示",
        "settings_floating_button" to "フローティングボタンのカスタマイズ",
        "settings_floating_size" to "フローティングボタンのサイズ",
        "settings_floating_alpha" to "フローティングボタンの不透明度",
        "settings_about" to "アプリ情報とサポート",
        "settings_how_to_use" to "クイック設定タイルのガイド",
        "settings_support" to "テクニカルサポートとコミュニティ",
        "settings_version" to "製品バージョン 1.0",
        "theme_dark" to "ダーク",
        "theme_light" to "ライト",
        "theme_system" to "システムデフォルト",
        "color_sapphire" to "サファイア",
        "color_emerald" to "エメラルド",
        "color_amethyst" to "アメジスト",
        "color_sunset" to "サンセット",
        "color_crimson" to "クリムゾン",
        "color_teal" to "ティール",
        "connected_status" to "接続済み",
        "settings_dynamic_m3" to "ダイナミック M3",
        "engine_core_title" to "特権エンジン (Castix Core)",
        "engine_prefix" to "エンジン:",
        "engine_active" to "アクティブ",
        "engine_status_desc" to "システムエンジンが接続され、バックグラウンド制限を回避して画面をオフにする準備が整いました。",
        "engine_check_button" to "特権の確認と再初期化",
        "settings_support_email" to "support@elhizazi.me",
        "settings_version_info" to "バージョン 1.0 (Build 2026.09) • Android 17 アーキテクト",
        "clock_style_digital" to "デジタル時計",
        "clock_style_minimal" to "ミニマリスト",
        "clock_style_glow" to "ネオングロウ",
        "clock_style_analog" to "クラシックアナログ",
        "clock_style_retro" to "レトロフリップ",
        "clock_style_text_word" to "ワードクロック",
        "clock_style_pixel_airy" to "Pixel エアリー",
        "clock_style_material_expressive" to "Material エクスプレッシブ",
        "clock_customization_title" to "クロックスタジオ",
        "clock_customization_desc" to "AMOLED 時計を細かく調整",
        "clock_scale_label" to "サイズ",
        "clock_position_label" to "垂直位置",
        "clock_spacing_label" to "間隔",
        "clock_style_large_center" to "ラージセンター",
        "clock_style_stacked" to "スタック時刻",
        "clock_style_mono_line" to "モノライン",
        "clock_style_dashboard" to "データダッシュボード",
        "amoled_preview_title" to "AMOLED ライブプレビュー",
        "amoled_preview_desc" to "100% ピュアブラックピクセルによるライブプレビューでバッテリーを節約",
        "amoled_btn_test" to "今すぐ画面オフをテスト",
        "amoled_clock_section" to "時計のデザインとスタイル",
        "amoled_clock_section_desc" to "時計の外観とアンビエントレイアウトを選択します",
        "amoled_display_elements" to "画面表示要素",
        "amoled_display_elements_desc" to "バッテリーを節約するためにブラックアウト中に表示する要素を設定します",
        "show_battery_label" to "バッテリー残量と状態",
        "show_battery_desc" to "微妙なネオングロウで現在のバッテリーレベルを表示します",
        "show_date_label" to "日付と曜日",
        "show_date_desc" to "時計の下に現在の日付を表示します",
        "show_app_badge_label" to "アクティブアプリバッジ",
        "show_app_badge_desc" to "バックグラウンドで再生中のアプリ名を表示します",
        "show_playback_timer_label" to "再生セッションタイマー",
        "show_playback_timer_desc" to "連続再生時間を追跡します",
        "burn_in_label" to "ピクセルシフト (焼き付き防止)",
        "burn_in_desc" to "OLEDディスプレイを保護するため、要素を定期的にわずかに移動させます",
        "custom_inscription_label" to "カスタム署名 / スローガン",
        "custom_inscription_desc" to "ブラックアウト中にパーソナライズされたフレーズを表示します",
        "custom_inscription_hint" to "カスタムスローガンを入力...",
        "floating_customization_section" to "フローティングボタンの外観",
        "floating_customization_desc" to "サイズ、不透明度、およびハプティックフィードバックを調整します",
        "floating_size_label" to "ボタンのサイズ",
        "floating_alpha_label" to "ボタンの不透明度",
        "floating_haptic_label" to "ハプティックフィードバック",
        "floating_haptic_desc" to "フローティングボタンを押したときに短く振動します",
        "qs_tile_tip" to "クイック設定タイル: 画面の上から下にスワイプし、「編集」をタップして、「画面オフ」タイルをアクティブなタイルにドラッグします。",
        "engine_selector_title" to "特権エンジン",
        "engine_selector_desc" to "デバイスの特権エンジンを選択してアクティブにします",
        "active_engine_label" to "アクティブなエンジン",
        "engine_ready" to "アクティブ & 承認済み",
        "engine_not_ready" to "非アクティブ • 設定が必要です",
        "status_escalation_tier" to "特権階層",
        "status_service_running" to "サービス状態",
        "status_overlay_perm" to "オーバーレイ権限",
        "status_granted" to "許可済み",
        "status_denied" to "拒否",
        "status_active" to "アクティブ",
        "status_checking" to "確認中…",
        "status_available" to "利用可能",
        "status_perm_needed" to "権限が必要です",
        "status_inactive" to "サービス停止中",
        "status_missing" to "未インストール",
        "status_error" to "エラー",
        "status_none_active" to "非アクティブ",
        "engine_none_active_hint" to "現在アクティブな特権エンジンはありません。エンジンを選択してアクティブにしてください。",
        "engine_btn_grant_perm" to "権限を許可",
        "engine_btn_setup_guide" to "セットアップガイド",
        "engine_btn_start_service" to "サービスを開始",
        "engine_btn_open_lsposed" to "LSPosedを開く",
        "engine_btn_open_manager" to "マネージャーを開く",
        "engine_btn_activate" to "アクティブ化",
        "engine_btn_retry" to "再試行",
        "playback_utility_title" to "再生の最適化",
        "playback_utility_subtitle" to "システムレベルのバックグラウンドバイパス",
        "btn_apply_all" to "すべて適用",
        "task_doze_title" to "バッテリー最適化の除外 (Doze)",
        "task_doze_desc" to "ディープスリープ中もオーディオパイプラインをアクティブに保ちます。",
        "task_standby_title" to "スタンバイバケット アクティブ",
        "task_standby_desc" to "OSの制限なしでCPUとネットワークの割り当てを保証します。",
        "task_appops_title" to "バックグラウンド AppOps",
        "task_appops_desc" to "制限のないバックグラウンド実行権限を付与します。",
        "task_phantom_title" to "ファントムプロセス停止の無効化",
        "task_phantom_desc" to "Androidが再生プロセスを強制終了するのを防ぎます。",
        "lsposed_spoofing_title" to "オーディオフォーカスフック (LSPosed)",
        "lsposed_spoofing_desc" to "音量低下とフォーカス放棄の要求をブロックします。",
        "task_enforced" to "有効",
        "btn_reapply" to "再適用",
        "terminal_title" to "特権コンソール",
        "terminal_subtitle" to "メディア管理とシステムシェルコマンドを実行します",
        "terminal_placeholder" to "シェルコマンドを入力 (例: dumpsys media_session)...",
        "terminal_card_title" to "特権コンソール",
        "btn_clear_terminal" to "ログを消去",
        "terminal_input_hint" to "シェルコマンドを入力...",
        "btn_run" to "実行",
        "terminal_empty_msg" to "コンソールは空です。コマンドまたはバイパスタスクを実行してください。",
        "quick_commands_label" to "クイックコマンド:",
        "settings_black_screen_subtitle" to "時計のスタイル、バッジ、および画面オフの動作をカスタマイズ",
        "settings_show_app_badge_desc" to "ブラックアウト中にアクティブなバックグラウンドアプリを表示します",
        "settings_double_tap_wake" to "ダブルタップでスリープ解除",
        "settings_double_tap_wake_desc" to "暗転画面の任意の場所をダブルタップしてロック解除します",
        "settings_zero_brightness" to "ゼロバックライト (0%)",
        "settings_zero_brightness_desc" to "バックライトをハードウェアの最小レベルまで暗くしてバッテリーを節約します",
        "settings_floating_subtitle" to "フローティングボタンのサイズと不透明度を調整します",
        "settings_about_subtitle" to "ユーザーガイド、クイック設定タイル、サポート",
        "settings_version_detail" to "バージョン 1.0 (Build 2026.09) • Android 17 対応",
        "settings_edition" to "Castix プロダクションエディション",
        "app_name" to "Castix",
        "subtitle_arch" to "Android 17 アーキテクト",
        "btn_enable_accessibility" to "ユーザー補助を有効にする",
        "btn_auto_grant_engine" to "エンジン経由で許可",
        "floating_perm_required_title" to "権限が必要です",
        "floating_perm_required_desc" to "オーバーレイ権限が必要です。",
        "floating_accessibility_tip_title" to "瞬時検出",
        "floating_accessibility_tip_desc" to "検出のためにユーザー補助サービスを有効にしてください。",
        "lock_screen_unsecured" to "スワイプ",
        "lock_screen_wakelock" to "WakeLock",
        "lock_screen_wakelock_active" to "アクティブ",
        "lock_screen_wakelock_ready" to "スタンバイ",
        "lock_screen_battery_opt" to "バッテリー最適化",
        "lock_screen_battery_unrestricted" to "除外済み",
        "lock_screen_battery_restricted" to "最適化済み",
        "lock_screen_btn_disable_battery_opt" to "最適化から除外",
        "lock_screen_battery_auto_grant" to "自動ホワイトリスト",
        "permission_required_tag" to "権限が必要です",
        "black_screen_status_engaged" to "画面オフ",
        "lock_screen_feature_1_title" to "安全なサポート",
        "lock_screen_feature_1_desc" to "安全に動作します。",
        "lock_screen_feature_2_title" to "途切れない音声",
        "lock_screen_feature_2_desc" to "優先順位を維持します。",
        "lock_screen_feature_3_title" to "クイックロック解除",
        "lock_screen_feature_3_desc" to "ダブルタップで終了します。",
        "lock_screen_btn_security_settings" to "セキュリティ設定",
        "target_apps_selected_summary" to "%1\$d アプリケーションを選択済み",
        "target_apps_empty" to "アプリが見つかりません",
        "target_apps_media_badge" to "メディア",
        "section_engine_selector" to "特権戦略",
        "section_service_status" to "システム状態",
        "section_playback_ops" to "再生ツール",
        "section_terminal" to "特権コンソール",
        "engines_title" to "システムエンジン",
        "engines_subtitle" to "ワンタップでエンジンを切り替え",
        "engine_details_btn" to "エンジンの詳細",
        "engine_perm_steps_title" to "認証ステップ",
        "engine_capabilities_title" to "機能",
        "shizuku_name" to "Shizuku",
        "dhizuku_name" to "Dhizuku",
        "root_name" to "Root (su)",
        "lsposed_name" to "LSPosed",
        "lspatch_name" to "LSPatch (Rootなし)",
        "accessibility_name" to "ユーザー補助サービス",
        "accessibility_service_desc" to "Castixがアプリを検出し再生を維持できるようにします。",
        "playback_bypasses_title" to "バックグラウンド操作",
        "playback_bypasses_subtitle" to "再生の中断を防ぐ",
        "btn_execute_all" to "すべて実行",
        "lsposed_hook_title" to "LSPosed メディアフック",
        "lsposed_hook_desc" to "画面オフ時の停止を防ぎます",
        "terminal_input_placeholder" to "シェルコマンドを入力...",
        "btn_clear_logs" to "ログを消去",
        "terminal_empty_logs" to "コンソールは空です。コマンドを実行してください。",
        "settings_language_choose_title" to "言語を選択",
        "settings_language_choose_desc" to "希望の言語を選択してください",
        "settings_double_tap" to "ダブルタップでスリープ解除",
        "settings_double_tap_desc" to "ダブルタップですぐに終了します",
        "settings_floating_button_subtitle" to "サイズと不透明度を調整します",
        "hex_presets_label" to "プリセットパレット",
        "how_to_use_step_1" to "通知シェードを2回下にスワイプします。",
        "how_to_use_step_2" to "鉛筆アイコンをタップして編集します。",
        "how_to_use_step_3" to "Castix \\'画面オフ\\' タイルを上にドラッグします。",
        "how_to_use_step_4" to "再生中にタイルをタップして画面をオフにしてください！",
        "support_desc" to "Castixはバックグラウンド再生に最適化されています。",
        "support_channel" to "公式サポートチャンネル",
        "notification_title" to "Castix • 再生アクティブ",
        "notification_text" to "音声保護中 • タップして画面をオフ",
        "notification_action_black_screen" to "画面をオフ",
        "notification_action_stop" to "サービスを停止",
        "battery_stable" to "バッテリー安定",
        "runtime_environment" to "実行環境",
        "target_platform" to "ターゲットプラットフォーム",
        "api_level" to "API レベル",
        "selinux_mode" to "SELinux モード",
        "device_hardware" to "ハードウェア",
        "architecture" to "アーキテクチャ",
        "compatibility_banner_title" to "システム: Android %1\$s (API %2\$d)",
        "compatibility_banner_desc" to "すべてのツールは互換性があります。",
        "engine_available_active" to "アクティブ",
        "engine_permission_needed" to "権限が必要です",
        "btn_activate" to "アクティブ化",
        "service_status_title" to "システム状態",
        "live_ipc_monitors" to "IPC モニター",
        "status_perm_required" to "権限が必要",
        "black_screen_continuous_play" to "連続再生",
        "black_screen_app_playing" to "%1\$s • 連続再生",
        "black_screen_long_press_unlock" to "長押しでロック解除",
        "engine_dialog_guide_title" to "Architecture & Diagnostics",
        "engine_dialog_current_status" to "Current status:",
        "engine_dialog_build" to "Build: %1\$s",
        "engine_dialog_open_manager" to "Open %1\$s App",
        "engine_dialog_root_note" to "%1\$s detected. Open it to manage superuser access.",
        "engine_dialog_lsposed_note" to "Open LSPosed Manager, enable the Castix module, select target applications, then restart the target apps.",
        "engine_dialog_root_request" to "Request Root (su)",
        "engine_dialog_accessibility_request" to "Open Accessibility Settings",
        "engine_dialog_close" to "Close",
        "engine_dialog_root_steps" to "1. Tap 'Request Root (su)' below to send a request to the root service.\n2. Approve the permission request in your root manager.",
        "engine_dialog_shizuku_steps" to "3. Open Shizuku, pair with the service, then start it.\n4. Tap 'Grant Permission' below to authorize Castix.",
        "engine_dialog_dhizuku_step" to "3. Open Dhizuku and grant permission to Castix.",
        "engine_dialog_lsposed_step" to "3. Open LSPosed, enable the Castix module, and select the target media apps.",
        "engine_dialog_accessibility_steps" to "1. Tap 'Grant Permission' below.\n2. The Accessibility settings screen will open automatically.",
        "lsposed_dialog_title" to "Activate LSPosed Module",
        "lsposed_dialog_version" to "LSPosed 2.2.0 (API 102 Zygisk)",
        "lsposed_dialog_close" to "Close",
        "lsposed_dialog_framework_status" to "Framework status:",
        "lsposed_dialog_framework_active" to "LSPosed is enabled and active on your device",
        "lsposed_dialog_module_status" to "Castix module status:",
        "lsposed_dialog_instructions_title" to "How to activate Castix inside LSPosed:",
        "lsposed_dialog_instructions" to "1. Open the LSPosed Manager installed on your device.",
        "lsposed_dialog_confirm" to "Confirm module activation (I enabled it in LSPosed)",
        "lsposed_dialog_rescan" to "Re-check module status automatically",
        "shizuku_dialog_title" to "Request Shizuku / Shevery Permission",
        "shizuku_dialog_subtitle" to "System Binder IPC permission without root",
        "shizuku_dialog_close" to "Close",
        "shizuku_dialog_installed" to "Installed application:",
        "shizuku_dialog_server_status" to "Shizuku server status:",
        "shizuku_dialog_castix_permission" to "Castix permission:",
        "shizuku_dialog_activation_title" to "Activation method:",
        "shizuku_dialog_activation_steps" to "1. If the service is stopped, open Shizuku, Shevery, or Shizuku+ and start it (via wireless debugging or root).\n2. After the service starts, tap 'Direct Permission Request' below to authorize Castix.",
        "shizuku_dialog_permission_request" to "Permission already granted (request again)",
        "shizuku_dialog_direct_request" to "Direct Permission Request",
        "shizuku_dialog_open_manager" to "Open Manager App (%1\$s)",
        "shizuku_dialog_rescan" to "Re-check connection and refresh status",
        "terminal_prompt" to "android17@sysarchitect ~ #",
        "notification_service_title" to "Castix • Background Playback",
        "notification_service_text" to "Protection is active • Tap to turn off the screen or open the app",
        "notification_action_black_screen_ui" to "Turn Screen Off (Black Screen)",
        "black_screen_session_timer" to "Active Session: %1\$dm",
        "amoled_preview_time" to "TIME • %1\$s",
        "amoled_preview_battery" to "88%% • Battery Optimal",
        "amoled_preview_session" to "Active Session: 25m",
        "amoled_preview_now_playing" to "Now Playing: YouTube",

        "black_screen_clock_time_ar" to "TIME • %1\$d:%2\$d",
        "black_screen_clock_time_en" to "TIME • %1\$d:%2\$d",

    )
}
