package me.elhizazi.Castix.privilege.ui

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.platform.LocalContext
import java.util.Locale

data class AppLanguage(
    val code: String,
    val nativeName: String,
    val englishName: String,
    val isRtl: Boolean = false
)

object LanguageRegistry {
    val supportedLanguages: List<AppLanguage>
        get() = listOf(
            AppLanguage(code = "en", nativeName = "English", englishName = "English"),
            AppLanguage(code = "ar", nativeName = "العربية", englishName = "Arabic", isRtl = true)
        ) + AppStringsSecondary.languages

    fun findLanguage(code: String): AppLanguage {
        val effective = AppStrings.resolveEffectiveLanguage(code)
        return supportedLanguages.firstOrNull { it.code.equals(effective, ignoreCase = true) }
            ?: supportedLanguages.first()
    }
}

object AppStrings {
    private val coreCodes = setOf("en", "ar")

    private val supportedCodes: Set<String>
        get() = coreCodes + AppStringsSecondary.languages.map { it.code }

    fun resolveEffectiveLanguage(lang: String): String {
        val normalized = lang.trim().lowercase(Locale.ROOT)
        if (normalized in supportedCodes) return normalized

        val systemLanguage = Locale.getDefault().language.lowercase(Locale.ROOT)
        return if (systemLanguage in supportedCodes) systemLanguage else "en"
    }

    fun get(key: String, lang: String = "auto", vararg args: Any?): String {
        val effective = resolveEffectiveLanguage(lang)
        val template = when (effective) {
            "ar" -> ar[key] ?: en[key]
            else -> AppStringsSecondary.maps[effective]?.get(key) ?: en[key]
        } ?: key

        return if (args.isEmpty()) template else {
            try {
                String.format(Locale.forLanguageTag(effective), template, *args)
            } catch (_: Exception) {
                template
            }
        }
    }

    fun getForContext(context: Context, key: String, vararg args: Any?): String {
        val language = AppSettingsManager.getInstance(context).settings.value.language
        return get(key, language, *args)
    }

    @Composable
    fun text(key: String, vararg args: Any?): String {
        val context = LocalContext.current
        val settings by AppSettingsManager.getInstance(context).settings.collectAsState()
        return get(key, settings.language, *args)
    }

    val en = mapOf(
        "nav_home" to "Home",
        "nav_amoled" to "AMOLED",
        "nav_engines" to "Engines",
        "nav_settings" to "Settings",
        "app_title" to "Castix",
        "app_subtitle" to "Screen-Off & Background Playback",
        "app_tag_pro" to "PRO",
        "black_screen_title" to "AMOLED Black Screen",
        "black_screen_desc" to "Turn off screen pixels while media continues playing",
        "black_screen_action_on" to "Turn Screen Off",
        "black_screen_action_off" to "Dismiss Black Screen",
        "black_screen_tip" to "Tip: Double-tap anywhere to dismiss, or single-tap to view clock for 10s.",
        "save_power_badge" to "100% Power Saved",
        "black_screen_unlock_hint" to "Double-tap to unlock",
        "black_screen_playing_fallback" to "Playing in background",
        "black_screen_active_state" to "Active (Pixels Off)",
        "black_screen_inactive_state" to "Screen On",
        "floating_title" to "Floating Button",
        "floating_desc" to "Quick screen-off button over video players",
        "floating_status_enabled" to "Active • Ready",
        "floating_status_disabled" to "Disabled",
        "floating_status_active" to "Active",
        "floating_mode_label" to "Display Mode",
        "floating_mode_selected_apps" to "Selected Apps",
        "floating_mode_always_visible" to "Always Visible",
        "floating_selected_apps_count" to "apps selected",
        "floating_scope_label" to "Display Scope:",
        "scope_selected_apps" to "Selected Apps Only",
        "scope_all_apps" to "Always on Screen",
        "selected_apps_count" to "apps selected",
        "btn_choose_apps" to "Choose Apps",
        "target_apps" to "Target Apps",
        "floating_btn_manage_apps" to "Target Apps",
        "overlay_perm_required" to "Overlay Permission Required",
        "overlay_perm_warning_title" to "Overlay Permission Required",
        "overlay_perm_warning_desc" to "Display over other apps is required to black out screen pixels while keeping playback active.",
        "open_settings" to "Open Settings",
        "grant_via_engine" to "Auto Grant via Engine",
        "accessibility_warning" to "Accessibility service is disabled. Required to detect when target apps open.",
        "enable_accessibility" to "Enable Service",
        "service_title" to "Background Service",
        "service_subtitle" to "Keeps audio playing and bypasses lock screen pause",
        "service_running" to "Active • Connected",
        "service_stopped" to "Stopped",
        "service_status_label" to "Service Status",
        "service_btn_start" to "Start Service",
        "service_btn_stop" to "Stop Service",
        "service_btn_restart" to "Restart",
        "service_mode_label" to "System Priority:",
        "service_lockscreen_bypass_label" to "WakeLock Bypass",
        "service_wakelock_engaged" to "Active (Audio Protected)",
        "service_wakelock_idle" to "Standby",
        "status_bar_notice" to "Accessible from Quick Settings Tile",
        "lock_screen_title" to "Lock Screen Compatibility",
        "lock_screen_subtitle" to "Audio continues playing when device is locked",
        "lock_screen_phone_protection" to "Security",
        "lock_screen_secured" to "Secured (PIN / Biometric)",
        "lock_screen_power_saving" to "Battery Optimization",
        "lock_screen_unrestricted" to "Exempted (Unrestricted)",
        "lock_screen_restricted" to "Optimized (May pause audio)",
        "lock_screen_ambient_mode" to "Always-On Display",
        "lock_screen_ambient_ready" to "Compatible",
        "btn_fix_battery_optimization" to "Exempt Battery Optimization",
        "lock_screen_tip" to "Audio and media notifications stay active on the lock screen without unexpected pauses.",
        "target_apps_sheet_title" to "Target Applications",
        "target_apps_sheet_subtitle" to "Floating button appears automatically only when these apps are open",
        "search_apps_placeholder" to "Search by app or package...",
        "btn_select_all" to "Select All",
        "btn_deselect_all" to "Deselect All",
        "btn_clear_all" to "Clear Selection",
        "btn_done" to "Done",
        "no_apps_found" to "No matching applications found",
        "engine_desc_shizuku" to "Direct Binder IPC through an authorized Shizuku service.",
        "engine_desc_dhizuku" to "Device Owner delegation for system policy and background controls.",
        "engine_desc_root" to "Direct superuser shell execution through the device root manager.",
        "engine_desc_lsposed" to "Runtime hooks injected through the LSPosed framework into supported processes.",
        "engine_desc_lspatch" to "Rootless Xposed hooks embedded into patched target APKs.",
        "engine_desc_accessibility" to "Android Accessibility service for foreground detection and playback support.",
        "engine_arch_shizuku" to "Remote Binder Service (ADB/root)",
        "engine_arch_dhizuku" to "Device Owner policy service",
        "engine_arch_root" to "Superuser shell (UID 0)",
        "engine_arch_lsposed" to "ART/Zygote runtime hooks",
        "engine_arch_lspatch" to "Rootless APK/Dex loader",
        "engine_arch_accessibility" to "Android Accessibility Framework",
        "engine_status_detail_active" to "This engine is currently authorized and ready to use.",
        "engine_status_detail_inactive" to "The engine is detected, but it is not currently active.",
        "engine_status_detail_permission" to "The engine is running or installed, but Castix still needs its permission.",
        "engine_status_detail_available" to "Available to use, but not currently active.",
        "engine_status_detail_missing" to "This engine was not detected on the device.",
        "engine_status_detail_error" to "The engine reported an error and is not ready.",
        "engine_root_detected" to "Detected: %1\$s",
        "engine_root_kernel_note" to "On %1\$s/APatch, root prompts may not appear automatically. Open the manager, find Castix under Superuser, and enable its access.",
        "engine_root_app_note" to "%1\$s was detected. Open it to check Castix Superuser access.",
        "engine_lsposed_activation_title" to "Activate Castix in LSPosed",
        "engine_lsposed_activation_text" to "Open LSPosed Manager, enable the Castix module under Modules, select the target applications, then restart them.",
        "engine_detail_root" to "The Root engine uses the device superuser service to execute system commands with UID 0.",
        "engine_detail_shizuku" to "Shizuku provides Castix with authorized Binder IPC access through its system service.",
        "engine_detail_dhizuku" to "Dhizuku provides Device Owner based system policy access for supported operations.",
        "engine_detail_lsposed" to "LSPosed injects Castix hooks into supported ART/Zygote processes. It only works when the Castix module is actually enabled and loaded by LSPosed.",
        "engine_detail_lspatch" to "LSPatch embeds Castix Xposed hooks into a patched target APK. It only works inside an APK that has actually been patched and loaded.",
        "engine_detail_accessibility" to "Android Accessibility provides a zero-root service used for foreground application detection and related controls.",
        "engine_setup_root" to "1. Ensure a root manager is installed and the device is rooted.\n2. Tap 'Request Root (su)' below.\n3. Approve Castix in the root manager.",
        "engine_setup_shizuku" to "1. Install Shizuku.\n2. Enable Wireless Debugging.\n3. Start the Shizuku service.\n4. Grant Castix permission.",
        "engine_setup_dhizuku" to "1. Install Dhizuku.\n2. Set it as Device Owner using its documented ADB procedure.\n3. Grant Castix access in Dhizuku.",
        "engine_setup_lsposed" to "1. Enable Zygisk in your root manager.\n2. Install and start LSPosed.\n3. Enable the Castix module and select its target applications.\n4. Restart the target applications.",
        "engine_setup_lspatch" to "1. Install LSPatch.\n2. Select the target player APK.\n3. Patch the APK with Castix and install the patched APK.",
        "engine_setup_accessibility" to "1. Tap 'Request Permission' below.\n2. Android Accessibility settings will open.\n3. Enable the Castix service.",
        "engine_sheet_title" to "Privilege Engine Details",
        "engine_status_label" to "Status",
        "engine_privilege_label" to "Privilege Level",
        "engine_capabilities_label" to "Engine Capabilities",
        "engine_commands_label" to "Quick Commands",
        "btn_request_perm" to "Grant Permission",
        "btn_grant_overlay" to "Grant Permission",
        "btn_test_engine" to "Test Engine",
        "btn_close" to "Close",
        "btn_cancel" to "Cancel",
        "btn_apply" to "Apply",
        "btn_refresh" to "Refresh Status",
        "btn_dismiss" to "Dismiss",
        "btn_execute" to "Execute",
        "btn_clear" to "Clear Logs",
        "lang_sheet_title" to "App Language",
        "lang_sheet_subtitle" to "Select your preferred language. Interface layout direction updates immediately.",
        "lang_search_placeholder" to "Search language...",
        "future_languages_note" to "Language support is managed centrally in AppStrings.kt.",
        "lang_auto" to "Follow System (Auto)",
        "lang_en" to "English",
        "lang_ar" to "Arabic (العربية)",
        "lang_fr" to "French (Français)",
        "lang_es" to "Spanish (Español)",
        "lang_pt" to "Portuguese (Português)",
        "lang_de" to "German (Deutsch)",
        "lang_it" to "Italian (Italiano)",
        "lang_ru" to "Russian (Русский)",
        "lang_tr" to "Turkish (Türkçe)",
        "hex_sheet_title" to "Custom Accent Color",
        "hex_sheet_subtitle" to "Tap or drag on the color wheel to select your preferred accent color.",
        "hex_input_label" to "HEX Code (e.g. #00E5FF)",
        "hex_custom_button" to "Custom Hex",
        "settings_appearance" to "Appearance & Theme",
        "settings_appearance_desc" to "Control appearance, themes, and dynamic Android colors",
        "settings_display_mode" to "Display Mode",
        "settings_color_palette" to "Color Palette",
        "settings_ui_scale_title" to "UI & Font Scale",
        "settings_ui_scale_desc" to "Adjust interface scaling and typography.",
        "settings_theme" to "Theme Mode",
        "settings_language" to "App Language",
        "settings_language_current" to "Current",
        "settings_accent" to "Accent Color",
        "settings_black_screen" to "Black Screen Customization",
        "settings_clock_style" to "Clock Style",
        "settings_show_app_badge" to "Show Active App Badge",
        "settings_floating_button" to "Floating Button Customization",
        "settings_floating_size" to "Floating Button Size",
        "settings_floating_alpha" to "Floating Button Opacity",
        "settings_about" to "About & Support",
        "settings_how_to_use" to "Quick Settings Tile Guide",
        "settings_support" to "Technical Support & Community",
        "settings_version" to "Production Version 1.0",
        "theme_dark" to "Dark",
        "theme_light" to "Light",
        "theme_system" to "System Default",
        "color_sapphire" to "Sapphire",
        "color_emerald" to "Emerald",
        "color_amethyst" to "Amethyst",
        "color_sunset" to "Sunset",
        "color_crimson" to "Crimson",
        "color_teal" to "Teal",
        "connected_status" to "Connected",
        "settings_dynamic_m3" to "Dynamic M3",
        "engine_core_title" to "Privilege Engine (Castix Core)",
        "engine_prefix" to "Engine:",
        "engine_active" to "Active",
        "engine_status_desc" to "System engine is connected and ready to bypass background restrictions and turn off screen pixels.",
        "engine_check_button" to "Check Privileges & Reinitialize",
        "settings_support_email" to "support@elhizazi.me",
        "settings_version_info" to "Version 1.0 (Build 2026.09) • Android 17 Architect",
        "clock_style_digital" to "Digital Clean",
        "clock_style_minimal" to "Minimalist",
        "clock_style_glow" to "Neon Glow",
        "clock_style_analog" to "Classic Analog",
        "clock_style_retro" to "Retro Flip",
        "clock_style_text_word" to "Word Clock",
        "clock_style_pixel_airy" to "Pixel Airy",
        "clock_style_material_expressive" to "Material Expressive",
        "clock_customization_title" to "Clock Studio",
        "clock_customization_desc" to "Fine-tune the clock for your AMOLED screen",
        "clock_scale_label" to "Scale",
        "clock_position_label" to "Vertical Position",
        "clock_spacing_label" to "Spacing",
        "clock_style_large_center" to "Large Center",
        "clock_style_stacked" to "Stacked Time",
        "clock_style_mono_line" to "Mono Line",
        "clock_style_dashboard" to "Data Dashboard",
        "amoled_preview_title" to "AMOLED Live Preview",
        "amoled_preview_desc" to "Real-time preview with 100% pure black pixels to save battery power",
        "amoled_btn_test" to "Test Screen-Off Now",
        "amoled_clock_section" to "Clock Design & Styles",
        "amoled_clock_section_desc" to "Select clock appearance and ambient layout",
        "amoled_display_elements" to "Screen Display Elements",
        "amoled_display_elements_desc" to "Configure elements shown during screen blackout to conserve battery",
        "show_battery_label" to "Battery Level & Health",
        "show_battery_desc" to "Display current battery level with a subtle neon glow",
        "show_date_label" to "Day & Date",
        "show_date_desc" to "Display current day and calendar date below clock",
        "show_app_badge_label" to "Active App Badge",
        "show_app_badge_desc" to "Display the name of the app playing in background",
        "show_playback_timer_label" to "Playback Session Timer",
        "show_playback_timer_desc" to "Track continuous listening duration",
        "burn_in_label" to "Pixel Shift (Burn-In Protection)",
        "burn_in_desc" to "Slightly shifts elements periodically to protect OLED displays",
        "custom_inscription_label" to "Custom Subtitle / Signature",
        "custom_inscription_desc" to "Show a discreet personalized phrase or slogan during blackout",
        "custom_inscription_hint" to "Enter custom inscription...",
        "floating_customization_section" to "Floating Button Appearance",
        "floating_customization_desc" to "Adjust size, opacity, and haptic feedback of the floating trigger",
        "floating_size_label" to "Button Size",
        "floating_alpha_label" to "Button Opacity",
        "floating_haptic_label" to "Haptic Feedback",
        "floating_haptic_desc" to "Vibrate briefly when floating button is pressed",
        "qs_tile_tip" to "Quick Settings Tile: Swipe down from the top of your screen, tap 'Edit' and drag the 'Screen Off' tile into your active tiles.",
        "engine_selector_title" to "Privilege Engines",
        "engine_selector_desc" to "Select and activate the privilege engine on your device",
        "active_engine_label" to "Active Engine",
        "engine_ready" to "Active & Authorized",
        "engine_not_ready" to "Inactive • Setup Needed",
        "status_escalation_tier" to "Privilege Tier",
        "status_service_running" to "Service Status",
        "status_overlay_perm" to "Overlay Permission",
        "status_granted" to "Granted",
        "status_denied" to "Denied",
        "status_active" to "Active",
        "status_checking" to "Checking…",
        "status_available" to "Available",
        "status_perm_needed" to "Permission Needed",
        "status_inactive" to "Service Stopped",
        "status_missing" to "Not Installed",
        "status_error" to "Error",
        "status_none_active" to "Inactive",
        "engine_none_active_hint" to "No privilege engine is currently active. Select and activate an engine for full control.",
        "engine_btn_grant_perm" to "Grant Permission",
        "engine_btn_setup_guide" to "Setup Guide",
        "engine_btn_start_service" to "Start Service",
        "engine_btn_open_lsposed" to "Open LSPosed",
        "engine_btn_open_manager" to "Open Manager",
        "engine_btn_activate" to "Activate",
        "engine_btn_retry" to "Retry",
        "playback_utility_title" to "Playback Optimizations",
        "playback_utility_subtitle" to "System-level background bypasses",
        "btn_apply_all" to "Apply All",
        "task_doze_title" to "Battery Exemption (Doze)",
        "task_doze_desc" to "Keeps audio pipeline active during deep idle.",
        "task_standby_title" to "Standby Bucket ACTIVE",
        "task_standby_desc" to "Guarantees CPU & network quota without OS throttling.",
        "task_appops_title" to "Background AppOps",
        "task_appops_desc" to "Grants unrestricted background execution privilege.",
        "task_phantom_title" to "Disable Phantom Process Killer",
        "task_phantom_desc" to "Prevents Android from killing child playback processes.",
        "lsposed_spoofing_title" to "Audio Focus Hook (LSPosed)",
        "lsposed_spoofing_desc" to "Suppresses audio ducking and abandon requests.",
        "task_enforced" to "ACTIVE",
        "btn_reapply" to "Re-apply",
        "terminal_title" to "Privileged Console",
        "terminal_subtitle" to "Execute media management and system shell commands",
        "terminal_placeholder" to "Enter shell command (e.g. dumpsys media_session)...",
        "terminal_card_title" to "Privileged Console",
        "btn_clear_terminal" to "Clear Logs",
        "terminal_input_hint" to "Enter shell command...",
        "btn_run" to "Run",
        "terminal_empty_msg" to "Console is empty. Run a command or bypass task.",
        "quick_commands_label" to "Quick Commands:",
        "settings_black_screen_subtitle" to "Customize clock style, badges and blackout behavior",
        "settings_show_app_badge_desc" to "Display active background app during blackout",
        "settings_double_tap_wake" to "Double Tap to Wake",
        "settings_double_tap_wake_desc" to "Double-tap anywhere on black screen to unlock",
        "settings_zero_brightness" to "Zero Backlight (0%)",
        "settings_zero_brightness_desc" to "Dim backlight to hardware minimum for battery savings",
        "settings_floating_subtitle" to "Adjust size and opacity of the floating button",
        "settings_about_subtitle" to "User guide, quick settings tile and support",
        "settings_version_detail" to "Version 1.0 (Build 2026.09) • Android 17 Compatible",
        "settings_edition" to "Castix Production Edition",
        "app_name" to "Castix",
        "subtitle_arch" to "Android 17 System Architect",
        "btn_enable_accessibility" to "Enable Accessibility",
        "btn_auto_grant_engine" to "Auto Grant via Engine",
        "floating_perm_required_title" to "Overlay Permission Required",
        "floating_perm_required_desc" to "Floating button requires display over other apps permission.",
        "floating_accessibility_tip_title" to "Instant App Detection",
        "floating_accessibility_tip_desc" to "Enable Castix Accessibility Service for zero-delay detection of video apps.",
        "lock_screen_unsecured" to "Swipe Only",
        "lock_screen_wakelock" to "WakeLock",
        "lock_screen_wakelock_active" to "Active",
        "lock_screen_wakelock_ready" to "Standby",
        "lock_screen_battery_opt" to "Battery Saver",
        "lock_screen_battery_unrestricted" to "Unrestricted",
        "lock_screen_battery_restricted" to "Restricted",
        "lock_screen_btn_disable_battery_opt" to "Disable Battery Restrictions",
        "lock_screen_battery_auto_grant" to "Auto-Whitelist (Root/Shizuku)",
        "permission_required_tag" to "Permission Required",
        "black_screen_status_engaged" to "Screen Off",
        "lock_screen_feature_1_title" to "Secure Lock Support",
        "lock_screen_feature_1_desc" to "Operates safely behind lock screen without exposing data.",
        "lock_screen_feature_2_title" to "Uninterrupted Audio",
        "lock_screen_feature_2_desc" to "Media sessions maintain continuous foreground priority.",
        "lock_screen_feature_3_title" to "Double-Tap Unlock",
        "lock_screen_feature_3_desc" to "Double-tap anywhere to dismiss black screen immediately.",
        "lock_screen_btn_security_settings" to "Security Settings",
        "target_apps_selected_summary" to "%1\$d applications selected",
        "target_apps_empty" to "No matching apps found",
        "target_apps_media_badge" to "Media Player",
        "section_engine_selector" to "Privilege Escalation Strategy",
        "section_service_status" to "System Backend Status",
        "section_playback_ops" to "Background Playback & Keep-Alive Tools",
        "section_terminal" to "Privileged Command Console",
        "engines_title" to "System Privilege Engines",
        "engines_subtitle" to "Toggle or switch your privilege engine with a single tap",
        "engine_details_btn" to "Engine Details",
        "engine_perm_steps_title" to "Authorization Steps",
        "engine_capabilities_title" to "Capabilities",
        "shizuku_name" to "Shizuku",
        "dhizuku_name" to "Dhizuku",
        "root_name" to "Root (su)",
        "lsposed_name" to "LSPosed",
        "lspatch_name" to "LSPatch (Rootless)",
        "accessibility_name" to "Accessibility Service",
        "accessibility_service_desc" to "Allows Castix to detect foreground applications instantly, show the floating trigger, and maintain playback priority without root.",
        "playback_bypasses_title" to "Background Playback Operations",
        "playback_bypasses_subtitle" to "System-level bypasses for uninterrupted video and audio",
        "btn_execute_all" to "Execute All Bypasses",
        "lsposed_hook_title" to "LSPosed Media Hook",
        "lsposed_hook_desc" to "Injects media session hooks to prevent players from pausing on screen off",
        "terminal_input_placeholder" to "Enter shell command (e.g., pm list packages)...",
        "btn_clear_logs" to "Clear Console",
        "terminal_empty_logs" to "Console output is empty. Execute a task or command above.",
        "settings_language_choose_title" to "Select Application Language",
        "settings_language_choose_desc" to "Choose your preferred interface language for Castix, with automatic layout direction switching (RTL / LTR)",
        "settings_double_tap" to "Double-Tap to Wake",
        "settings_double_tap_desc" to "Double-tap anywhere on the black screen to dismiss immediately",
        "settings_floating_button_subtitle" to "Adjust size and opacity of the hollow circular floating disc",
        "hex_presets_label" to "Preset Palettes",
        "how_to_use_step_1" to "Swipe down the notification shade twice to expose all Quick Settings tiles.",
        "how_to_use_step_2" to "Tap the pencil icon or \\'Edit\\' button to manage available tiles.",
        "how_to_use_step_3" to "Drag the Castix \\'Black Screen\\' tile into your active top tiles.",
        "how_to_use_step_4" to "Now while playing video or music, tap the tile to black out all pixels while background playback continues seamlessly!",
        "support_desc" to "Castix is dedicated to seamless background playback and pure AMOLED screen-off power saving.",
        "support_channel" to "Official Support Channel",
        "notification_title" to "Castix • Background Playback Active",
        "notification_text" to "Audio protection running • Tap to black out screen or open app",
        "notification_action_black_screen" to "Screen Off (Black Screen)",
        "notification_action_stop" to "Stop Service",
        "battery_stable" to "Stable Battery",
        "runtime_environment" to "Runtime Environment",
        "target_platform" to "Target Platform",
        "api_level" to "API Level",
        "selinux_mode" to "SELinux Mode",
        "device_hardware" to "Device Hardware",
        "architecture" to "Architecture",
        "compatibility_banner_title" to "Current System: Android %1\$s (API %2\$d)",
        "compatibility_banner_desc" to "All background playback bypasses and process protection tools are fully compatible with your system.",
        "engine_available_active" to "Active",
        "engine_permission_needed" to "Permission Needed",
        "btn_activate" to "Activate",
        "service_status_title" to "System Backend Status",
        "live_ipc_monitors" to "Live IPC Monitors",
        "status_perm_required" to "Perm Needed",
        "black_screen_continuous_play" to "Continuous background playback",
        "black_screen_app_playing" to "%1\$s • Continuous Play",
        "black_screen_long_press_unlock" to "Long press to unlock",
        "engine_dialog_guide_title" to "Architecture & Diagnostics",
        "engine_dialog_current_status" to "Current status:",
        "engine_dialog_build" to "Build: %1\$s",
        "engine_dialog_open_manager" to "Open %1\$s App",
        "engine_dialog_root_note" to "%1\$s detected. Open it to manage superuser access.",
        "engine_dialog_lsposed_note" to "Open LSPosed Manager, enable the Castix module, select target applications, then restart the target apps.",
        "engine_dialog_root_request" to "Request Root (su)",
        "engine_dialog_accessibility_request" to "Open Accessibility Settings",
        "engine_dialog_close" to "Close",
        "engine_dialog_root_steps" to "1. Tap 'Request Root (su)' below to send a request to the root service.\n2. Approve the permission request in your root manager.",
        "engine_dialog_shizuku_steps" to "3. Open Shizuku, pair with the service, then start it.\n4. Tap 'Grant Permission' below to authorize Castix.",
        "engine_dialog_dhizuku_step" to "3. Open Dhizuku and grant permission to Castix.",
        "engine_dialog_lsposed_step" to "3. Open LSPosed, enable the Castix module, and select the target media apps.",
        "engine_dialog_accessibility_steps" to "1. Tap 'Grant Permission' below.\n2. The Accessibility settings screen will open automatically.",
        "lsposed_dialog_title" to "Activate LSPosed Module",
        "lsposed_dialog_version" to "LSPosed 2.2.0 (API 102 Zygisk)",
        "lsposed_dialog_close" to "Close",
        "lsposed_dialog_framework_status" to "Framework status:",
        "lsposed_dialog_framework_active" to "LSPosed is enabled and active on your device",
        "lsposed_dialog_module_status" to "Castix module status:",
        "lsposed_dialog_instructions_title" to "How to activate Castix inside LSPosed:",
        "lsposed_dialog_instructions" to "1. Open the LSPosed Manager installed on your device.",
        "lsposed_dialog_confirm" to "Confirm module activation (I enabled it in LSPosed)",
        "lsposed_dialog_rescan" to "Re-check module status automatically",
        "shizuku_dialog_title" to "Request Shizuku / Shevery Permission",
        "shizuku_dialog_subtitle" to "System Binder IPC permission without root",
        "shizuku_dialog_close" to "Close",
        "shizuku_dialog_installed" to "Installed application:",
        "shizuku_dialog_server_status" to "Shizuku server status:",
        "shizuku_dialog_castix_permission" to "Castix permission:",
        "shizuku_dialog_activation_title" to "Activation method:",
        "shizuku_dialog_activation_steps" to "1. If the service is stopped, open Shizuku, Shevery, or Shizuku+ and start it (via wireless debugging or root).\n2. After the service starts, tap 'Direct Permission Request' below to authorize Castix.",
        "shizuku_dialog_permission_request" to "Permission already granted (request again)",
        "shizuku_dialog_direct_request" to "Direct Permission Request",
        "shizuku_dialog_open_manager" to "Open Manager App (%1\$s)",
        "shizuku_dialog_rescan" to "Re-check connection and refresh status",
        "terminal_prompt" to "android17@sysarchitect ~ #",
        "notification_service_title" to "Castix • Background Playback",
        "notification_service_text" to "Protection is active • Tap to turn off the screen or open the app",
        "notification_action_black_screen_ui" to "Turn Screen Off (Black Screen)",
        "black_screen_session_timer" to "Active Session: %1\$dm",
        "amoled_preview_time" to "TIME • %1\$s",
        "amoled_preview_battery" to "88%% • Battery Optimal",
        "amoled_preview_session" to "Active Session: 25m",
        "amoled_preview_now_playing" to "Now Playing: YouTube",

        "black_screen_clock_time_ar" to "TIME • %1\$d:%2\$d",
        "black_screen_clock_time_en" to "TIME • %1\$d:%2\$d",

    )

    val ar = mapOf(
        "nav_home" to "الرئيسية",
        "nav_amoled" to "شاشة أموليد",
        "nav_engines" to "المحركات",
        "nav_settings" to "الإعدادات",
        "app_title" to "Castix",
        "app_subtitle" to "إطفاء الشاشة والتشغيل في الخلفية",
        "app_tag_pro" to "PRO",
        "black_screen_title" to "شاشة سوداء AMOLED",
        "black_screen_desc" to "إطفاء بكسلات الشاشة مع استمرار تشغيل الفيديو والصوت دون انقطاع",
        "black_screen_action_on" to "إطفاء الشاشة الآن",
        "black_screen_action_off" to "إلغاء الشاشة السوداء",
        "black_screen_tip" to "نصيحة: انقر مرتين في أي مكان على الشاشة السوداء لإلغاء القفل فوراً، أو نقرة واحدة لإظهار الساعة والبيانات لمدة 10 ثوانٍ.",
        "save_power_badge" to "توفير 100% طاقة الشاشة",
        "black_screen_unlock_hint" to "انقر مرتين للإلغاء",
        "black_screen_playing_fallback" to "تشغيل مستمر في الخلفية",
        "black_screen_active_state" to "الشاشة السوداء نشطة (البكسلات مطفأة)",
        "black_screen_inactive_state" to "الشاشة مضاءة (تشغيل عادي)",
        "floating_title" to "الزر العائم (قرص دائري)",
        "floating_desc" to "قرص دائري عائم شفاف يظهر حصرياً داخل التطبيقات المختارة لإطفاء الشاشة بنقرة واحدة بدون وميض",
        "floating_status_enabled" to "نشط وجاهز للتحكم السريع",
        "floating_status_disabled" to "معطّل",
        "floating_status_active" to "نشط وجاهز",
        "floating_mode_label" to "وضع الظهور",
        "floating_mode_selected_apps" to "في التطبيقات المحددة فقط",
        "floating_mode_always_visible" to "دائماً على الشاشة",
        "floating_selected_apps_count" to "تطبيق محدد",
        "floating_scope_label" to "نطاق ظهور الزر العائم:",
        "scope_selected_apps" to "التطبيقات المحددة فقط",
        "scope_all_apps" to "في كل مكان على الشاشة",
        "selected_apps_count" to "تطبيقاً محدداً",
        "btn_choose_apps" to "تحديد التطبيقات",
        "target_apps" to "اختيار التطبيقات",
        "floating_btn_manage_apps" to "تحديد التطبيقات المستهدفة",
        "overlay_perm_required" to "صلاحية الظهور فوق التطبيقات مطلوبة",
        "overlay_perm_warning_title" to "صلاحية الظهور فوق التطبيقات مطلوبة",
        "overlay_perm_warning_desc" to "يلزم منح صلاحية الظهور فوق التطبيقات لإطفاء بكسلات الشاشة مع إبقاء تشغيل الصوت بالخلفية نشطاً.",
        "open_settings" to "فتح الإعدادات",
        "grant_via_engine" to "منح تلقائي عبر المحرك",
        "accessibility_warning" to "خدمة إمكانية الوصول غير مفعلة. مطلوبة لرصد فتح التطبيقات المستهدفة فورياً.",
        "enable_accessibility" to "تفعيل إمكانية الوصول",
        "service_title" to "خدمة التشغيل في الخلفية",
        "service_subtitle" to "خدمة النظام الأساسية لحجز أولوية الصوت وتجاوز قفل الشاشة",
        "service_running" to "نشطة • متصلة بشريط الحالة",
        "service_stopped" to "متوقفة • اضغط للبدء",
        "service_status_label" to "حالة الخدمة",
        "service_btn_start" to "بدء الخدمة",
        "service_btn_stop" to "إيقاف الخدمة",
        "service_btn_restart" to "إعادة تشغيل",
        "service_mode_label" to "وضع أولوية النظام:",
        "service_lockscreen_bypass_label" to "تجاوز قفل الشاشة",
        "service_wakelock_engaged" to "قفل المعالج WakeLock نشط (الصوت محمي)",
        "service_wakelock_idle" to "وضع الاستعداد",
        "status_bar_notice" to "متاح من لوحة الاختصارات السريعة",
        "lock_screen_title" to "التوافق مع قفل وحماية الجهاز",
        "lock_screen_subtitle" to "متوافق 100% — يستمر الصوت بالعمل حتى عند قفل الهاتف برمز PIN أو البصمة",
        "lock_screen_phone_protection" to "حماية الهاتف",
        "lock_screen_secured" to "مؤمّن",
        "lock_screen_power_saving" to "توفير البطارية",
        "lock_screen_unrestricted" to "مستثنى بالكامل (تشغيل بلا انقطاع)",
        "lock_screen_restricted" to "مقيد (قد يتوقف الصوت عند القفل)",
        "lock_screen_ambient_mode" to "شاشة Always-On Display",
        "lock_screen_ambient_ready" to "متوافق وجاهز",
        "btn_fix_battery_optimization" to "استثناء من توفير البطارية",
        "lock_screen_tip" to "تنبيه: يبقى إشعار التشغيل فعالاً على شاشة القفل وتستمر الموسيقى بدون أي انقطاع.",
        "target_apps_sheet_title" to "التطبيقات المستهدفة للزر العائم",
        "target_apps_sheet_subtitle" to "سيظهر الزر العائم تلقائياً فقط عند فتح هذه التطبيقات",
        "search_apps_placeholder" to "بحث باسم التطبيق أو الحزمة...",
        "btn_select_all" to "تحديد الكل",
        "btn_deselect_all" to "إلغاء تحديد الكل",
        "btn_clear_all" to "مسح الكل",
        "btn_done" to "تم",
        "no_apps_found" to "لم يتم العثور على تطبيقات مطابقة",
        "engine_desc_shizuku" to "اتصال Binder مباشر عبر خدمة Shizuku المصرح بها.",
        "engine_desc_dhizuku" to "تفويض مالك الجهاز للتحكم في سياسات النظام والمهام الخلفية.",
        "engine_desc_root" to "تنفيذ أوامر النظام مباشرة عبر خدمة الروت بصلاحية المستخدم الفائق.",
        "engine_desc_lsposed" to "خطافات تشغيلية يحقنها إطار LSPosed داخل العمليات المدعومة.",
        "engine_desc_lspatch" to "خطافات Xposed بدون روت مضمّنة داخل ملفات APK المعدلة فعلياً.",
        "engine_desc_accessibility" to "خدمة إمكانية الوصول في أندرويد لرصد التطبيق الأمامي ودعم التشغيل.",
        "engine_arch_shizuku" to "خدمة Binder عن بُعد (ADB/روت)",
        "engine_arch_dhizuku" to "خدمة سياسات مالك الجهاز",
        "engine_arch_root" to "طرفية الروت (UID 0)",
        "engine_arch_lsposed" to "خطافات ART/Zygote",
        "engine_arch_lspatch" to "محمّل APK/Dex بدون روت",
        "engine_arch_accessibility" to "إطار إمكانية الوصول في أندرويد",
        "engine_status_detail_active" to "هذا المحرك مصرح به حالياً وجاهز للاستخدام.",
        "engine_status_detail_inactive" to "تم اكتشاف المحرك، لكنه غير نشط حالياً.",
        "engine_status_detail_permission" to "المحرك مثبت أو يعمل، لكن Castix ما زال يحتاج إلى الصلاحية.",
        "engine_status_detail_available" to "متاح للاستخدام، لكنه غير نشط حالياً.",
        "engine_status_detail_missing" to "لم يتم اكتشاف هذا المحرك على الجهاز.",
        "engine_status_detail_error" to "أبلغ المحرك عن خطأ وهو غير جاهز.",
        "engine_root_detected" to "تم اكتشاف: %1\$s",
        "engine_root_kernel_note" to "في %1\$s/APatch قد لا تظهر نافذة الروت تلقائياً. افتح المدير، وابحث عن Castix ضمن Superuser، ثم فعّل الصلاحية.",
        "engine_root_app_note" to "تم اكتشاف %1\$s. افتحه للتحقق من صلاحية Superuser الخاصة بـ Castix.",
        "engine_lsposed_activation_title" to "تفعيل Castix داخل LSPosed",
        "engine_lsposed_activation_text" to "افتح مدير LSPosed، فعّل موديول Castix من قسم Modules، اختر التطبيقات المستهدفة، ثم أعد تشغيلها.",
        "engine_detail_root" to "يستخدم محرك الروت خدمة المستخدم الفائق لتنفيذ أوامر النظام بصلاحية UID 0.",
        "engine_detail_shizuku" to "يمنح Shizuku Castix وصول Binder مصرحاً به عبر خدمته النظامية.",
        "engine_detail_dhizuku" to "يوفر Dhizuku وصولاً إلى سياسات النظام اعتماداً على صلاحية مالك الجهاز للعمليات المدعومة.",
        "engine_detail_lsposed" to "يحقن LSPosed خطافات Castix داخل عمليات ART/Zygote المدعومة. يعمل فقط عندما يكون موديول Castix مفعلاً ومحموّلاً فعلياً بواسطة LSPosed.",
        "engine_detail_lspatch" to "يضمّن LSPatch خطافات Castix داخل APK معدل. يعمل فقط داخل APK تم تعديله وتحميله فعلياً بواسطة LSPatch.",
        "engine_detail_accessibility" to "توفر إمكانية الوصول خدمة رسمية بدون روت لرصد التطبيقات الأمامية وتنفيذ عناصر التحكم المرتبطة بها.",
        "engine_setup_root" to "1. تأكد من تثبيت مدير روت وأن الجهاز مروّت.\n2. اضغط 'طلب إذن الروت (su)' بالأسفل.\n3. وافق على Castix من مدير الروت.",
        "engine_setup_shizuku" to "1. ثبّت Shizuku.\n2. فعّل تصحيح الأخطاء اللاسلكي.\n3. شغّل خدمة Shizuku.\n4. امنح Castix الصلاحية.",
        "engine_setup_dhizuku" to "1. ثبّت Dhizuku.\n2. عيّنه كمالك للجهاز باستخدام إجراء ADB الموثق له.\n3. امنح Castix الصلاحية داخل Dhizuku.",
        "engine_setup_lsposed" to "1. فعّل Zygisk في مدير الروت.\n2. ثبّت LSPosed وشغّله.\n3. فعّل موديول Castix وحدد التطبيقات المستهدفة.\n4. أعد تشغيل التطبيقات المستهدفة.",
        "engine_setup_lspatch" to "1. ثبّت LSPatch.\n2. اختر APK المشغل المستهدف.\n3. عدّل APK باستخدام Castix وثبّت النسخة المعدلة.",
        "engine_setup_accessibility" to "1. اضغط 'طلب الصلاحية' بالأسفل.\n2. ستفتح إعدادات إمكانية الوصول في أندرويد.\n3. فعّل خدمة Castix.",
        "engine_sheet_title" to "تفاصيل محرك الصلاحيات",
        "engine_status_label" to "الحالة الحالية",
        "engine_privilege_label" to "مستوى الصلاحية",
        "engine_capabilities_label" to "قدرات المحرك",
        "engine_commands_label" to "أوامر سريعة متاحة",
        "btn_request_perm" to "منح الصلاحية",
        "btn_grant_overlay" to "منح الصلاحية",
        "btn_test_engine" to "اختبار المحرك",
        "btn_close" to "إغلاق",
        "btn_cancel" to "إلغاء",
        "btn_apply" to "تطبيق",
        "btn_refresh" to "تحديث الحالة",
        "btn_dismiss" to "تجاهل",
        "btn_execute" to "تنفيذ",
        "btn_clear" to "مسح السجل",
        "lang_sheet_title" to "لغة التطبيق",
        "lang_sheet_subtitle" to "اختر لغة الواجهة المفضلة، وسيتغير اتجاه التصميم وعناصره فورياً.",
        "lang_search_placeholder" to "ابحث عن لغة...",
        "future_languages_note" to "يمكنك إضافة أي لغة إضافية يدوياً عبر ملف strings.xml بكل سهولة.",
        "lang_auto" to "حسب لغة النظام (تلقائي)",
        "lang_en" to "الإنجليزية",
        "lang_ar" to "العربية",
        "hex_sheet_title" to "لون مخصص للمظهر",
        "hex_sheet_subtitle" to "انقر أو اسحب في أي مكان على عجلة الألوان لاختيار لونك المفضل بدقة.",
        "hex_input_label" to "رمز HEX",
        "hex_custom_button" to "Hex مخصص",
        "settings_appearance" to "المظهر والتصميم",
        "settings_appearance_desc" to "التحكم في المظهر والسمات وألوان النظام المتوافقة مع أندرويد 17",
        "settings_display_mode" to "وضع العرض",
        "settings_color_palette" to "لوحة الألوان",
        "settings_ui_scale_title" to "مقياس الواجهة والخطوط",
        "settings_ui_scale_desc" to "اضبط مقياس عناصر واجهة المستخدم والخطوط لراحة العين والاستخدام الأمثل.",
        "settings_theme" to "وضع المظهر",
        "settings_language" to "لغة التطبيق",
        "settings_language_current" to "الحالية",
        "settings_accent" to "لون النظام المخصص",
        "settings_black_screen" to "تخصيص عرض الشاشة السوداء",
        "settings_clock_style" to "شكل الساعة",
        "settings_show_app_badge" to "عرض اسم التطبيق المشغل بالخلفية",
        "settings_floating_button" to "تخصيص الزر العائم",
        "settings_floating_size" to "حجم الزر العائم",
        "settings_floating_alpha" to "شفافية الزر العائم",
        "settings_about" to "حول التطبيق والدعم",
        "settings_how_to_use" to "طريقة الاستخدام وشريط الحالة",
        "settings_support" to "الدعم الفني والمجتمع",
        "settings_version" to "الإصدار الإنتاجي 1.0",
        "theme_dark" to "داكن",
        "theme_light" to "فاتح",
        "theme_system" to "تلقائي (حسب النظام)",
        "color_sapphire" to "ياقوتي",
        "color_emerald" to "زمردي",
        "color_amethyst" to "جمشت",
        "color_sunset" to "غروب",
        "color_crimson" to "قرمزي",
        "color_teal" to "فيروزي",
        "connected_status" to "متصل",
        "settings_dynamic_m3" to "Dynamic M3",
        "engine_core_title" to "محرك الصلاحيات (Castix Core)",
        "engine_prefix" to "المحرك:",
        "engine_active" to "نشط",
        "engine_status_desc" to "محرك النظام متصل وجاهز لتجاوز قيود الخلفية وإطفاء بكسلات الشاشة.",
        "engine_check_button" to "فحص الصلاحيات وإعادة التهيئة",
        "settings_support_email" to "support@elhizazi.me",
        "settings_version_info" to "الإصدار 1.0 (Build 2026.09) • Android 17 Architect",
        "clock_style_digital" to "رقمي حديث",
        "clock_style_minimal" to "بسيط مدمج",
        "clock_style_glow" to "نيون متوهج",
        "clock_style_analog" to "عقارب كلاسيكية",
        "clock_style_retro" to "ريترو فليب",
        "clock_style_text_word" to "ساعة لفظية",
        "clock_style_pixel_airy" to "بيكسل الهوائي",
        "clock_style_material_expressive" to "ماتيريال تعبيري",
        "clock_customization_title" to "استوديو الساعة",
        "clock_customization_desc" to "اضبط الساعة بدقة لشاشة AMOLED",
        "clock_scale_label" to "الحجم",
        "clock_position_label" to "الموضع العمودي",
        "clock_spacing_label" to "التباعد",
        "clock_style_large_center" to "رقمية كبيرة في الوسط",
        "clock_style_stacked" to "الوقت عمودي",
        "clock_style_mono_line" to "سطر أحادي",
        "clock_style_dashboard" to "لوحة البيانات",
        "amoled_preview_title" to "معاينة حية لشاشة AMOLED",
        "amoled_preview_desc" to "محاكاة فورية لمظهر الشاشة بالكامل مع بكسلات سوداء نقية 100% لتوفير الطاقة",
        "amoled_btn_test" to "تجربة الشاشة الآن",
        "amoled_clock_section" to "أنماط وتصميم الساعة",
        "amoled_clock_section_desc" to "اختر النمط المناسب لشكل الوقت والتصميم العام",
        "amoled_display_elements" to "العناصر المعروضة على الشاشة",
        "amoled_display_elements_desc" to "تحديد البيانات التي ترغب في إظهارها أو إخفائها لتوفير الطاقة",
        "show_battery_label" to "نسبة وحالة شحن البطارية",
        "show_battery_desc" to "عرض مؤشر شحن البطارية بلون نيون مميز",
        "show_date_label" to "اليوم والتاريخ",
        "show_date_desc" to "عرض اليوم والتاريخ الحاليين أسفل الساعة",
        "show_app_badge_label" to "شارة التطبيق المشغل حالياً",
        "show_app_badge_desc" to "عرض اسم التطبيق (مثل يوتيوب أو سبوتيفاي) المشغل بالخلفية",
        "show_playback_timer_label" to "عداد وقت الاستماع المستمر",
        "show_playback_timer_desc" to "تتبع مدة جلسة التشغيل الحالية بدون انقطاع",
        "burn_in_label" to "حماية الشاشة من الاحتراق",
        "burn_in_desc" to "إزاحة بكسلات الساعة والعناصر طفيفاً كل دقيقة لحماية لوحات OLED وأموليد من التطبيع",
        "custom_inscription_label" to "نص أو شعار مخصص",
        "custom_inscription_desc" to "إظهار عبارة أو اسم أو توقيع خافت أسفل الشاشة السوداء",
        "custom_inscription_hint" to "اكتب نصاً مخصصاً...",
        "floating_customization_section" to "تخصيص أبعاد ومظهر الزر العائم",
        "floating_customization_desc" to "التحكم في حجم وشفافية واهتزاز القرص الدائري العائم",
        "floating_size_label" to "حجم القرص العائم",
        "floating_alpha_label" to "شفافية القرص العائم",
        "floating_haptic_label" to "الاهتزاز اللمسي عند اللمس",
        "floating_haptic_desc" to "نبضة اهتزاز ناعمة عند لمس الزر العائم لإطفاء الشاشة",
        "qs_tile_tip" to "ميزة شريط الحالة: اسحب شريط الهاتف العلوي للأسفل، ثم اضغط على زر 'تعديل' وأضف أيقونة 'إطفاء الشاشة' من Castix للوصول السريع.",
        "engine_selector_title" to "محركات صلاحيات النظام",
        "engine_selector_desc" to "تفعيل أو تبديل محرك الصلاحيات المتاح على جهازك",
        "active_engine_label" to "المحرك النشط حالياً",
        "engine_ready" to "نشط ومصرّح",
        "engine_not_ready" to "غير مفعل • يتطلب إعداد",
        "status_escalation_tier" to "رتبة الصلاحية",
        "status_service_running" to "حالة الخدمة",
        "status_overlay_perm" to "صلاحية الظهور فوق التطبيقات",
        "status_granted" to "ممنوح",
        "status_denied" to "مرفوض",
        "status_active" to "نشط ومصرّح",
        "status_checking" to "جارٍ الفحص…",
        "status_available" to "متاح للتفعيل",
        "status_perm_needed" to "يتطلب إذناً",
        "status_inactive" to "الخدمة متوقفة",
        "status_missing" to "غير مثبت",
        "status_error" to "خطأ في المحرك",
        "status_none_active" to "غير نشط",
        "engine_none_active_hint" to "لا يوجد أي محرك صلاحيات نشط حالياً. اختر محركاً وقم بتفعيله للتحكم الكامل.",
        "engine_btn_grant_perm" to "منح الإذن",
        "engine_btn_setup_guide" to "دليل التثبيت",
        "engine_btn_start_service" to "بدء الخدمة",
        "engine_btn_open_lsposed" to "فتح LSPosed",
        "engine_btn_open_manager" to "فتح المدير",
        "engine_btn_activate" to "تفعيل",
        "engine_btn_retry" to "إعادة المحاولة",
        "playback_utility_title" to "أدوات التشغيل في أندرويد 17",
        "playback_utility_subtitle" to "تجاوزات على مستوى النظام لاستمرار التشغيل",
        "btn_apply_all" to "تطبيق الكل",
        "task_doze_title" to "استثناء توفير الطاقة Doze",
        "task_doze_desc" to "إبقاء تدفق الصوت نشطاً أثناء السكون العميق.",
        "task_standby_title" to "تصنيف الاستعداد النشط",
        "task_standby_desc" to "ضمان حصة المعالج والشبكة دون تقييد من النظام.",
        "task_appops_title" to "صلاحية التشغيل بالخلفية AppOps",
        "task_appops_desc" to "منح صلاحية التشغيل بالخلفية المباشرة للتطبيق.",
        "task_phantom_title" to "تعطيل قاتل العمليات الوهمية",
        "task_phantom_desc" to "منع أندرويد من إنهاء العمليات الفرعية للتشغيل.",
        "lsposed_spoofing_title" to "اعتراض تركيز الصوت",
        "lsposed_spoofing_desc" to "منع كتم الصوت وتجاوز طلبات التخلي عن التركيز.",
        "task_enforced" to "نشط ومطبق",
        "btn_reapply" to "إعادة التطبيق",
        "terminal_title" to "الطرفية وأوامر النظام",
        "terminal_subtitle" to "تنفيذ أوامر إدارة الوسائط وتشغيل الخلفية في النظام",
        "terminal_placeholder" to "أدخل الأمر هنا...",
        "terminal_card_title" to "الطرفية وأوامر النظام",
        "btn_clear_terminal" to "مسح السجل",
        "terminal_input_hint" to "أدخل الأمر هنا...",
        "btn_run" to "تنفيذ",
        "terminal_empty_msg" to "السجل فارغ. نفّذ أمراً أو مهمة تجاوز.",
        "quick_commands_label" to "أوامر سريعة:",
        "settings_black_screen_subtitle" to "تخصيص نمط الساعة والبيانات المعروضة على الشاشة السوداء",
        "settings_show_app_badge_desc" to "عرض اسم التطبيق (مثل يوتيوب أو سبوتيفاي) الذي يعمل في الخلفية أثناء إطفاء الشاشة",
        "settings_double_tap_wake" to "إلغاء القفل بنقرتين",
        "settings_double_tap_wake_desc" to "انقر مرتين على أي مكان بالشاشة السوداء لإلغاء القفل فوراً",
        "settings_zero_brightness" to "تصفير إضاءة الشاشة تماماً",
        "settings_zero_brightness_desc" to "خفض إضاءة الشاشة الخلفية للحد الأدنى الممكن لتوفير أقصى طاقة بطارية",
        "settings_floating_subtitle" to "التحكم في أبعاد وشفافية القرص الدائري العائم",
        "settings_about_subtitle" to "دليل الاستخدام، شريط الحالة السريع والدعم الفني",
        "settings_version_detail" to "الإصدار 1.0 • متوافق مع أندرويد 17",
        "settings_edition" to "Castix Production Edition",
        "app_name" to "Castix",
        "subtitle_arch" to "مهندس نظام أندرويد 17",
        "btn_enable_accessibility" to "تفعيل إمكانية الوصول",
        "btn_auto_grant_engine" to "منح تلقائي عبر المحرك",
        "floating_perm_required_title" to "صلاحية الظهور فوق التطبيقات مطلوبة",
        "floating_perm_required_desc" to "يتطلب الزر العائم صلاحية الظهور فوق التطبيقات ليظهر فوق مشغلات الفيديو والوسائط.",
        "floating_accessibility_tip_title" to "الرصد الفوري عبر إمكانية الوصول",
        "floating_accessibility_tip_desc" to "فعّل خدمة إمكانية الوصول الخاصة بـ Castix لرصد فتح تطبيقات الفيديو بدون أي تأخير.",
        "lock_screen_unsecured" to "بدون رمز (سحب للشاشة)",
        "lock_screen_wakelock" to "التشغيل بالخلفية",
        "lock_screen_wakelock_active" to "قفل المعالج نشط • الصوت محمي",
        "lock_screen_wakelock_ready" to "جاهز عند القفل",
        "lock_screen_battery_opt" to "توفير الطاقة",
        "lock_screen_battery_unrestricted" to "غير مقيّد (مثالي عند القفل)",
        "lock_screen_battery_restricted" to "مقيّد (قد يقطع الصوت)",
        "lock_screen_btn_disable_battery_opt" to "استثناء من توفير البطارية لثبات القفل",
        "lock_screen_battery_auto_grant" to "استثناء تلقائي (Root/Shizuku)",
        "permission_required_tag" to "الإذن مطلوب",
        "black_screen_status_engaged" to "مطفأة الآن",
        "lock_screen_feature_1_title" to "حماية كاملة لبيانات الهاتف",
        "lock_screen_feature_1_desc" to "يعمل Castix بسلاسة خلف شاشة القفل دون كشف بياناتك الشخصية أو قفل جهازك.",
        "lock_screen_feature_2_title" to "انعدام انقطاع الصوت",
        "lock_screen_feature_2_desc" to "جلسات الوسائط محمية بأولوية واجهة المستخدم الأمامية لتفادي إيقافها بواسطة النظام.",
        "lock_screen_feature_3_title" to "إلغاء فوري بنقرتين",
        "lock_screen_feature_3_desc" to "ما عليك سوى النقر مرتين في أي مكان على الشاشة لإلغاء السواد فوراً.",
        "lock_screen_btn_security_settings" to "فتح إعدادات الأمان",
        "target_apps_selected_summary" to "تم تحديد %1\$d تطبيق",
        "target_apps_empty" to "لم يتم العثور على تطبيقات مطابقة",
        "target_apps_media_badge" to "مشغل وسائط",
        "section_engine_selector" to "استراتيجية رفع الصلاحيات",
        "section_service_status" to "حالة خوادم النظام",
        "section_playback_ops" to "أدوات استمرار وحماية التشغيل بالخلفية",
        "section_terminal" to "منصة الأوامر ذات الصلاحيات",
        "engines_title" to "محركات كسر قيود النظام",
        "engines_subtitle" to "تفعيل أو تبديل محرك الصلاحيات بنقرة واحدة",
        "engine_details_btn" to "تفاصيل المحرك",
        "engine_perm_steps_title" to "خطوات المصادقة والترخيص",
        "engine_capabilities_title" to "القدرات والصلاحيات",
        "shizuku_name" to "Shizuku",
        "dhizuku_name" to "Dhizuku",
        "root_name" to "Root (su)",
        "lsposed_name" to "LSPosed",
        "lspatch_name" to "LSPatch (بدون روت)",
        "accessibility_name" to "إمكانية الوصول (Accessibility)",
        "accessibility_service_desc" to "تتيح لـ Castix رصد فتح التطبيقات المستهدفة فوراً وإظهار الزر وتأمين استمرار الصوت بدون روت.",
        "playback_bypasses_title" to "عمليات التشغيل في الخلفية",
        "playback_bypasses_subtitle" to "تجاوز قيود النظام لتمكين استمرار الفيديو والصوت دون انقطاع",
        "btn_execute_all" to "تنفيذ كافة التجاوزات",
        "lsposed_hook_title" to "اعتراض وسائط LSPosed",
        "lsposed_hook_desc" to "حقن خطافات الوسائط لمنع مشغلات الفيديو من التوقف عند إطفاء الشاشة",
        "terminal_input_placeholder" to "أدخل أمر شيل (مثل pm list packages)...",
        "btn_clear_logs" to "مسح السجل",
        "terminal_empty_logs" to "سجل المنصة فارغ. نفّذ مهمة أو أدخل أمراً أعلاه.",
        "settings_language_choose_title" to "اختيار لغة التطبيق",
        "settings_language_choose_desc" to "اختر اللغة المفضلة لواجهة Castix مع دعم كامل لاتجاه الواجهة العربي (RTL)",
        "settings_double_tap" to "إلغاء القفل بنقرتين",
        "settings_double_tap_desc" to "انقر مرتين على أي مكان بالشاشة السوداء لإلغاء القفل فوراً",
        "settings_floating_button_subtitle" to "التحكم في أبعاد وشفافية القرص الدائري العائم",
        "hex_presets_label" to "لوحات الألوان الجاهزة",
        "how_to_use_step_1" to "اسحب شريط الإشعارات العلوي في هاتفك مرتين لفتح لوحة الإعدادات السريعة الكاملة.",
        "how_to_use_step_2" to "انقر على أيقونة القلم أو \\'تعديل\\' لإدارة أزرار شريط الحالة السريع.",
        "how_to_use_step_3" to "اسحب أيقونة \\'إطفاء الشاشة\\' من Castix وضعها ضمن أزرارك النشطة في الأعلى.",
        "how_to_use_step_4" to "الآن في أي وقت أثناء تشغيل أي فيديو، اسحب الشريط واضغط الزر لتطفئ الشاشة وتوفر 100% طاقة ويستمر الصوت فوراً!",
        "support_desc" to "تطبيق Castix مخصص لتمكين تشغيل الفيديو والوسائط بدون انقطاع مع إطفاء الشاشة لتوفير 100% من طاقة بكسلات الشاشة.",
        "support_channel" to "قناة الدعم الرسمية",
        "notification_title" to "Castix • التشغيل في الخلفية نشط",
        "notification_text" to "حماية الصوت قيد التشغيل • اضغط لإطفاء الشاشة أو فتح التطبيق",
        "notification_action_black_screen" to "إطفاء الشاشة (Black Screen)",
        "notification_action_stop" to "إيقاف الخدمة",
        "battery_stable" to "شحن مستقر",
        "runtime_environment" to "بيئة التشغيل",
        "target_platform" to "المنصة المستهدفة",
        "api_level" to "مستوى الواجهة (API)",
        "selinux_mode" to "وضع SELinux",
        "device_hardware" to "عتاد الجهاز",
        "architecture" to "معمارية المعالج",
        "compatibility_banner_title" to "نظام جهازك: أندرويد %1\$s (API %2\$d)",
        "compatibility_banner_desc" to "كافة أدوات حماية واستمرار التشغيل متوافقة وتعمل بنجاح على جهازك (مدعوم من Android 9 حتى 17+).",
        "engine_available_active" to "متاح ومفعّل",
        "engine_permission_needed" to "بحاجة إذن",
        "btn_activate" to "تفعيل",
        "service_status_title" to "حالة الخدمات الخلفية",
        "live_ipc_monitors" to "مراقبة الاتصال المباشر",
        "status_perm_required" to "إذن مطلوب",
        "black_screen_continuous_play" to "تشغيل مستمر في الخلفية",
        "black_screen_app_playing" to "%1\$s • تشغيل مستمر",
        "black_screen_long_press_unlock" to "اضغط مطولاً للإلغاء",
        "engine_dialog_guide_title" to "دليل ومعمارية الصلاحية",
        "engine_dialog_current_status" to "الحالة الراهنة:",
        "engine_dialog_build" to "Build: %1\$s",
        "engine_dialog_open_manager" to "فتح تطبيق %1\$s الآن",
        "engine_dialog_root_note" to "في أنظمة %1\$s و APatch، لا تظهر نافذة طلب الروت المنبثقة تلقائياً على الشاشة. يجب الدخول إلى تطبيق %1\$s، والبحث عن Castix في قائمة التطبيقات (Superuser)، وتفعيل الصلاحية يدوياً.",
        "engine_dialog_lsposed_note" to "لتفعيل موديول Castix، افتح تطبيق مدير LSPosed المثبت على جهازك، ادخل إلى قسم 'الإضافات' (Modules)، فعّل Castix واختر التطبيقات المستهدفة، ثم أعد تشغيل التطبيقات.",
        "engine_dialog_root_request" to "طلب إذن الروت (su)",
        "engine_dialog_accessibility_request" to "فتح إعدادات الوصول",
        "engine_dialog_close" to "إغلاق",
        "engine_dialog_root_steps" to "1. اضغط على زر 'طلب إذن الروت (su)' بالأسفل لإرسال طلب إلى خادم الروت.\n2. وافق على طلب الصلاحية من مدير الروت.",
        "engine_dialog_shizuku_steps" to "3. افتح Shizuku واقترن بالخدمة ثم اضغط بدء التشغيل (Start).\n4. اضغط 'طلب الصلاحية' بالأسفل لمنح الإذن لـ Castix.",
        "engine_dialog_dhizuku_step" to "3. افتح Dhizuku وامنح الإذن لتطبيق Castix.",
        "engine_dialog_lsposed_step" to "3. افتح تطبيق LSPosed وفعّل موديول Castix وحدد التطبيقات الصوتية المستهدفة.",
        "engine_dialog_accessibility_steps" to "1. اضغط على زر 'طلب الصلاحية' بالأسفل.\n2. ستفتح شاشة إعدادات إمكانية الوصول في الهاتف تلقائياً.",
        "lsposed_dialog_title" to "تفعيل موديول LSPosed",
        "lsposed_dialog_version" to "LSPosed 2.2.0 (API 102 Zygisk)",
        "lsposed_dialog_close" to "إغلاق",
        "lsposed_dialog_framework_status" to "حالة إطار العمل:",
        "lsposed_dialog_framework_active" to "LSPosed مفعل ونشط على جهازك",
        "lsposed_dialog_module_status" to "حالة موديول Castix:",
        "lsposed_dialog_instructions_title" to "طريقة تفعيل Castix داخل تطبيق LSPosed:",
        "lsposed_dialog_instructions" to "1. افتح تطبيق مدير LSPosed المثبت على جهازك.",
        "lsposed_dialog_confirm" to "تأكيد تفعيل الموديول (فعلته في LSPosed)",
        "lsposed_dialog_rescan" to "إعادة فحص حالة الموديول تلقائياً",
        "shizuku_dialog_title" to "طلب صلاحية Shizuku / Shevery",
        "shizuku_dialog_subtitle" to "إذن Binder IPC للنظام بدون روت",
        "shizuku_dialog_close" to "إغلاق",
        "shizuku_dialog_installed" to "التطبيق المثبت:",
        "shizuku_dialog_server_status" to "حالة خادم Shizuku:",
        "shizuku_dialog_castix_permission" to "صلاحية Castix:",
        "shizuku_dialog_activation_title" to "طريقة التفعيل:",
        "shizuku_dialog_activation_steps" to "1. إذا كانت الخدمة متوقفة: افتح تطبيق Shizuku أو Shevery أو Shizuku+ واضغط على 'بدء' (عبر تصحيح الأخطاء اللاسلكي أو الروت).\n2. بعد تشغيل الخدمة: اضغط على زر 'طلب الصلاحية المباشر' أدناه للموافقة على منح الإذن لـ Castix.",
        "shizuku_dialog_permission_request" to "الصلاحية ممنوحة بالفعل (إعادة طلب)",
        "shizuku_dialog_direct_request" to "طلب الصلاحية المباشر (Request Permission)",
        "shizuku_dialog_open_manager" to "فتح تطبيق المدير (%1\$s)",
        "shizuku_dialog_rescan" to "إعادة فحص الاتصال وتحديث الحالة",
        "terminal_prompt" to "android17@sysarchitect ~ #",
        "notification_service_title" to "Castix • الشاشة السوداء والخلفية",
        "notification_service_text" to "الحماية قيد التشغيل • اضغط لإطفاء الشاشة أو فتح التطبيق",
        "notification_action_black_screen_ui" to "إطفاء الشاشة (Black Screen)",
        "black_screen_session_timer" to "جلسة الاستماع: %1\$d دقيقة",
        "amoled_preview_time" to "الوقت • %1\$s",
        "amoled_preview_battery" to "88%% • بطارية مستقرة",
        "amoled_preview_session" to "جلسة الاستماع: 25 دقيقة",
        "amoled_preview_now_playing" to "مشغل الآن: YouTube",

        "black_screen_clock_time_ar" to "الساعة %1\$d : %2\$d",
        "black_screen_clock_time_en" to "TIME • %1\$d:%2\$d",

    )

}
